# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
stringData:
    client_id: ENC[AES256_GCM,data:gE4KtdBCQJvx+Fxuk7XhF7Q=,iv:fBlD0QWY4OifMMv8a7RKRnjN5E47bsb5/bsKNJtoXrI=,tag:xJ/hOaMMMzEXvfoZNZMb8w==,type:str]
    client_secret: ENC[AES256_GCM,data:die9SgroiyfS8b1bnhA7ntrH+wkKVDtbT8O5SguSxRqa8ufmXO8UNCIPjeJB1kSvPd2YfJl1SFevuNLbObq8ew==,iv:7HUHzg1Sh1daJpdT4NAKFSBkz1/7waAOC+mPKrlC4Hs=,tag:+s8W+zhFiu3n5h4cVqqa4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSjZ3V0xJTmQvUlI1SGo0
            S2Q2aXZ2ZXlFNVFCbWxVZUM5UjZJTTNtclM0CnpoOG5FZy9QRDdFazFaZWJ2eWRx
            eWE2OU9nck1SaE1vNk4vODN4ZzgyYzgKLS0tIG5ZK1NoRWYrcUs0RUx6Z01jOHhZ
            ZU95UEdOWGpQRDEzZW1YM3RKUkxNNk0K7n7mU3IMaBK75H1g3NqZ52hg5r6iSIW/
            EloU+EkAX9B9OVPvGhNq5E2XvDVGsQ9Trd3yvR1FEepJc6ylxf0yQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T01:47:14Z"
    mac: ENC[AES256_GCM,data:IzgYOplgpQm1kuIDD64hEdnh9ihOPT05fasGy9InhWOnWsTOQJz3VbVMhAbO3xZL/AJ9JaP6nzw8IMkxrhAZ9TMFiqgUj117cjChLiDnqhBR/9R1FrSL2K1lomUvEE5kPE0gPeAfleXnOkVp6clQZocl2/QvDeNZvrK9Oa0Ip7M=,iv:gKmbnRP4Vt1P9og2gTo0XeUafLaXnLUE3bJrTpCQH/c=,tag:fIqLOSdLJgIz1hF5RfsR8A==,type:str]
    version: 3.13.3
