# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: ipmi-credentials-shared
    namespace: medik8s-system
type: Opaque
stringData:
    ipaddr: ENC[AES256_GCM,data:/hcY0WNu4h3kpgF4Yg==,iv:IBQ0oTAO1td0wPkMZllSwTCM8nNRUx+m/9+N58IIEuE=,tag:Xpgp6LUKGPdKnEOVaDzHjw==,type:str]
    login: ENC[AES256_GCM,data:6TQqXp4=,iv:/xwYelRASUR7NXE05u1SgkaSACWEHbyQkx3xGciBa80=,tag:uPSfD7CkomxEE2oMqyEbzw==,type:str]
    passwd: ENC[AES256_GCM,data:wT/ms48=,iv:dmSvf+aVE5NU4hhRb0Ln5ThmfAPwcMKyhF6zOFquiTs=,tag:+p5rhk09DquxUHEiYXQ/Kw==,type:str]
    lanplus: ""
    node-name: ENC[AES256_GCM,data:UIQ/fhchX29eknTJyQ==,iv:5Y5J9G0j0MaV8+9BaNB+vw5Gtvm4s64YnwzomoFFvWw=,tag:A8zx+CLDwMt0cFkd61XPOw==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNGJEU05sWHFTWG0xMkZw
            NmpVTDcrWTU5TlpCRkRGYU8zTkZPYzZNT1NJCkdnM0NudWJrTU9vQXFFWW9MYXNK
            bzR4TjZ4dVRZTmoyaFJxQUwyOWN2YXMKLS0tIHA3Mlh4ZE04Y25WNGVZZUZHak5Y
            QmZXS3JTSVRCU2dPWklwazRYRjJ1dDQKv7tvMw3vdQL3KhDYb0sg1mPjQ2LK8znG
            Y1Hp1ox6uES516g8Q9BdUwLXPjE9XvpR6qrHlFjU2NBx1l6QDkEjCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T06:04:12Z"
    mac: ENC[AES256_GCM,data:LnJqTJBM+pROw2TdEdUMZHcwrE+3l1DEtKNnikiISD2ajCXWbmXpPci6PrD4OrdPkHHDoOw05SGJxMWP8+DWi371YIvi01r/STy4vFC03sYdjghOnXUCwo71fPBk6arMxez1/jm9LuspwIvsQ3GFBiLgZBCLe9sHUt4KwLfSm80=,iv:Sa84NjfZLPSiqm8fy0QMrR1kVi2cnrAw5iUol/4trFc=,tag:bembHM+71xHXdOOXlgfQ9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
