# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: ipmi-credentials-shared
    namespace: medik8s-system
type: Opaque
stringData:
    ipaddr: ENC[AES256_GCM,data:AsGITGOAkqPwZnlqYA==,iv:zOh1CXFMx2vD2n/cb1b9lVvoeqkMalgYY7n6RwBQvXY=,tag:eoPTjCyKEuk/aEAMiL2qCA==,type:str]
    login: ENC[AES256_GCM,data:kQC5gwk=,iv:qstHsxVtmqSYVNIPmkaMIrFsfc8kcI3y9OcAVPtPh00=,tag:Fh8wK7BRYDii6LtlB5zYsw==,type:str]
    passwd: ENC[AES256_GCM,data:8FrKkLQ=,iv:jg04DaHVL2+Y2a1/ImWJ/KyTApt8Q/+lYJWEComZdFU=,tag:xYhbF6PTf/4zdyy1Skm9lw==,type:str]
    lanplus: ENC[AES256_GCM,data:P5InJw==,iv:QIvVg2hFIIIuShAWdAt0ik4rDhGRbsmVDgzRLw08/jo=,tag:66Ea33417t9tVvWLDis9fA==,type:str]
    node-name: ENC[AES256_GCM,data:aE74MJdIPgCwb2EzKg==,iv:BmQx/RP1DZKSPOv2glqUp+tEleoYTxVOyJLdkokbTog=,tag:Y4cuVSyHph2ggU8ValiK7A==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZmhVY05YOXlYYmZXcHRP
            MlRzd2dscGZ4U2NEaVFiR1FqaVdHNFYxd1JNClRTS0JIYXV4eG00clFOcG5Eczhz
            bkhPbDE1SE1RVlRKZ1FJcyt4L3A2MzAKLS0tIDk0KzY4MWVLYUR5TWx5MU1rMGty
            dlRWUTBhaExoZHRacDM4MGExak5pQk0KbFuEmyq6FzG1P2Xk3eikgxPgx0dROTEJ
            b/PkNlCzjXbZQZMxhwzd9pqc4DVQxXS5O0ntVCe2Ag7ngpJTuDM8Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T05:54:05Z"
    mac: ENC[AES256_GCM,data:SJA4vB9CIVwZFzVcOxmpnwnvMXCT3VCywSqgx24/t+lMdWJTtZYBGo3i7sbpW1a2DokE4TXnzZ6b0qPyjIBbpiNUGqIQC239EX7WKPaR5HNd2pQcFlK7iQNoCNtbRSCUoqVHEP5aPA6fJsk3jBLc4qnE4KOqjecTwIPtmvGR7jA=,iv:yuOSKU+ZIiz9GG1tcIw1mFn8w7UmoiFghQjjU7yYsBk=,tag:ODpMFqwHTwsnzMpKpu29Ug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
