# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: melusine-ipmi-credentials
    namespace: medik8s-system
type: Opaque
stringData:
    --ip: ENC[AES256_GCM,data:JTPDX7hbZSnwC3a+Zw==,iv:nSoM4m5GGYMbB+jIiIHwCrTkDSN01gUb4pCN++nUE/0=,tag:Rh3nH2RGot8kZCKqeUwj7Q==,type:str]
    --username: ENC[AES256_GCM,data:F838d44=,iv:ipG1nPk10ejbwFlxcaXu/Kj+uNW8YFW2zU3oUZeNkAg=,tag:JBznCGcEd2cLM1rFJfK1kQ==,type:str]
    --password: ENC[AES256_GCM,data:Wtk4cXs=,iv:JomEE4MggW0G224D+a+pne+bbQJ28GsjWSq2bLHKyco=,tag:6kLfqataj0Q7l4Qa1U8Hrw==,type:str]
    --lanplus: ""
    node: ENC[AES256_GCM,data:1R5hjE2jbTqlBvhu4Q==,iv:q2sQsk2wCZY6YtRugxON5f2enUOMP3t35fuIbQnDeO0=,tag:N/l5Mv8qYSBYwRMRVopZFQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ3pSc3dzVC9aYXpvd3o2
            NEt2NlBRODdhOUFzbHpQdVRqckx6eElnc3hFCjcwVGpIeEpHMjZwNURMNlRiU04z
            TlRoWWRSakY0TzdiUU5YU1lZVG5aMDAKLS0tIHEzRWxVQ0Y1WUZEVTFTamQ0VUY5
            d1dBZCtWN1hJTE1ac0c1RDNDYTdWVVEKYW1sYgkVTaxeAjH9Ru8+zOiArHWESXCX
            PiVQYikO1m3oyNd98rFrQOKRFSMKpq0PyLf2Hy/MIdN57CokiR+P2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T06:04:12Z"
    mac: ENC[AES256_GCM,data:nHYlA6s2Qgmojub9S/v1A2Fp9MbbWylRGv7g5sQtIzjGqFx2b7bpOt0yHagebs37rDrxu41HwVVYSFH8qClrTEP8oDxcR8K/yPmlW1Tswmk3mzEE4rd4HHui31cN6wlk1GrqlFIE4cc/8hHtY18A02PdBMpPnUTvyhiDvJEa+Xw=,iv:KOw1Qch28mQvToSWfkoaF/0raojdrnnMq65KyjgJMIk=,tag:UBjWKdjWCwI6Mg2Q3KZWZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
