# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: proxmox-fence-credentials
    namespace: medik8s-system
type: Opaque
stringData:
    api-password: ENC[AES256_GCM,data:vJpfQAW2og9gn9gQmPYLOH7dIC62rO+mgh5IPIfWyrv6jfL8XxWD0qAqw8cYWvAlD3pIXiw=,iv:5uQVgEyfYXC1lrV/5TXMxHk1z6Vh87MrBh8zRsUILzQ=,tag:PZWwLTJUTSCcN8ZQhPDIjQ==,type:str]
    ipmi-host: ENC[AES256_GCM,data:+nBsyIvVBHqEKzgmFA==,iv:dDEouYMu0IYFVF/zZ2C8Tz6iYT9gxjnve4281Oh8wHE=,tag:NfSYXMWSYoa0URTJO7cZ9g==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dFo2ellPL2R2S1c4dVZs
            dW1rSnludnhCWWdsS01FM3c2Mld6c0pvR0drClJHMU9vdmJNSFU0QkNVWWtQUXky
            WUx2NU1mZ3lEMzNxdkl5TGpaUWxjUFkKLS0tIGRqRDF6TW5FVC9adkdiWGVMbVNr
            TkFTblljKzIyZ242VG9VMi9KZVpVaEEKOca9BWDgvzFQms6y84NktUPeBefF8+S9
            lHEvHwI1zXLPnrs4sr+X6M8fqsruAeZ9WvLHLay482KOL7joRDG2eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T01:30:50Z"
    mac: ENC[AES256_GCM,data:H/MXdOCiFvJXilclCL0WCRaopPy5eCCMlHXwi6/bdoAAcj/XJrOGP2D9BZ855xlxwVJwc/25qTlazJdPKirbI9BuzHssBUqpGPQxj91Se6aobIWFpqtx6gVYccpOr6/tKQwrAr1lKrjLkP1XN02syMIlumArQmI5xQ5jb9Ul2/8=,iv:7VV0RqOiyOL+VwBxbeH1LI0cgivwKj/9fgpYm/0j7tU=,tag:spKBv5lfWvwLgZmHGb4QfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
