# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: influxdb-backup-secret
    namespace: monitoring
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qFpF0TuXEdrsigsrLieqTjxlCJc=,iv:9bK5Z8qchA8BfdWuO7N16DCcy/b9Dvk8UVm6zKw5PFA=,tag:QSuSZjXTkHqzZt8ZIKpxig==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HjPcfOl4C5hAazDvgXbebWyIulVGJlZGac9SOHuRLw9gL7uKCqZv4w==,iv:PM3a7NnYGac2JN6o2Qq4wsZHZFMhujio1PU7Z4czbFM=,tag:J0xIdxMGkv9yaoMQ4poFcg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:KdBrIhv5p0Tox6uVO4wl8lQPW5D4/0DYJQWlzMkSOZ0x1CCKVwdYUzORHxI4OpW/8gJ0Oo3NekOug+i/Idd8JYI/2EWvVEWq1vuF4XYbIDIcnw6nTSYxsRbL+UyUwLfJ7lo=,iv:MNRb1UBYGZhqHHz8EkLezEzo/srYF9EmOMfENM5FpP4=,tag:c/OJHmttCqs0RjKecdk+PA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:KV5h8wRTK2CSK95UWY9uLylZgiw/BH4e2JqaI+Q/NgiNb8qKNcGdLvHpJ1o=,iv:6VZR4PtzYI7xX4NDYd6s/rOed3PL1w2kLR9mll2wzC0=,tag:tWo2nX03U7xTp6r0IH+n2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOGFHZWcxSE5zdjZVbnp0
            UVF3VmxCZXZyb0RHdUhmOEptNDNSQlVxQUZVCmJHMlluQm9xelA1M0dOR1dqem1m
            YStQZVVQSU5uZjFwQnlGMnZnS3JMNkEKLS0tICtaMTFtY2VTVzRMVXgvdk9EU3Jj
            cFdhbEdSNGgrSDlDcHMzSm1sTzZ0RnMKHBvoi6awlVoK/F9QFS9s64kc2xmjDrCi
            wwCHkdnsH+9KZ7Ch5Vuc7j7b/7haN06MMLgTv0I4fbDlY54Hm2j8GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T15:28:48Z"
    mac: ENC[AES256_GCM,data:s0oyzL02wstBYrZNs6KVtvM7yPowsE+kPlCBVAol9hUip8GuUvPJvHONgm8OETdGQtj7EBlwy5cgHRtw9AZNNZGB3d8M1HNtFdS7+JSREU3GO4E1wz18+dKcc2tVQdnlQH4IYrvtT3+QRJJrJCdnN5Zp0celYwuNTM8bt/y8PyQ=,iv:wISFgWpU9bdHa/FcfSdrgakc6L+oQGkgyAHcGI2gQeY=,tag:DQ2VA1aBnT9iFcL0zoGt9A==,type:str]
    version: 3.13.3
