# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: trino-catalog-credentials
    namespace: lakehouse
type: Opaque
stringData:
    aws-credentials.properties: ENC[AES256_GCM,data:dc+m/1GlqrwW3JGTY3NxgVWcagb9diSlmM82XDSEmryCtpMdUJSJaTFUnz33vPVtK03HoCaFCRi24hFz0yjsqW4M6XO8VqsGEcJq8DibU1s=,iv:VtjqrEvO3t244AnxWffsxmQDZV4ThKgpRpTCMQUGf/M=,tag:UxIclkfsG1Z/akJq7x2gXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRazNVVHdtTWw3S0V3Tytp
            R1JSRkFRMnR2eGVnWFZ6KzR1TEVRZEZQVTNrCkpRZUQ2US8zZ0hnOVBMLytaa1hN
            VDFGYXF5bGtTeFFwVXJGcnZvVXVLNnMKLS0tIEp1Vlg2M1pZNVZ5MTNER05NYUZj
            R3hRNUNxRUk1RTB2bUVLUGJHNjJkNG8KxDG7OMQILFq/j6AGcsl13WfIu3JqJpbG
            /IS5KYwRq6M1IcrvvgMBv3gt6U3wGpv1xKxyDJ3zrjHg3IFsgLY88g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T16:48:26Z"
    mac: ENC[AES256_GCM,data:VHhMoTSphIdFnRpoO8pyPLX+8GUQPtsVxpz6sSUsNgXjKpXnYHEnbi/QaNtNGCMml47puHL0fZ/BiR+TevTpNJgRsbQNafZhgCBm0mcJWmonCEhxNaN/WSK8Fua0117QrC3Nj3dpAIHovZA1YZrp6gv4AyrjXiyuIrHLZPBYxQ8=,iv:6NUbY4MYocHOQ9ZxE0202a2kv/NLN/9jxfxtoFdLaK8=,tag:Yws99z29tOrQHNJvd4si1w==,type:str]
    version: 3.13.3
