---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/csi.ceph.io/v1/driver.json
apiVersion: csi.ceph.io/v1
kind: Driver
metadata:
  name: rook-ceph.rbd.csi.ceph.com
  namespace: rook-ceph
spec:
  fsGroupPolicy: File
  controllerPlugin:
    tolerations:
      - key: node.kubernetes.io/disk-pressure
        operator: Exists
  nodePlugin:
    tolerations:
      - key: node.kubernetes.io/disk-pressure
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/csi.ceph.io/v1/driver.json
apiVersion: csi.ceph.io/v1
kind: Driver
metadata:
  name: rook-ceph.cephfs.csi.ceph.com
  namespace: rook-ceph
spec:
  fsGroupPolicy: File
  cephFsClientType: kernel
  controllerPlugin:
    tolerations:
      - key: node.kubernetes.io/disk-pressure
        operator: Exists
  nodePlugin:
    tolerations:
      - key: node.kubernetes.io/disk-pressure
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
