---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/csi.ceph.io/v1/operatorconfig.json
apiVersion: csi.ceph.io/v1
kind: OperatorConfig
metadata:
  name: ceph-csi-operator-config
  namespace: rook-ceph
spec:
  driverSpecDefaults:
    imageSet:
      name: rook-csi-operator-image-set-configmap
