# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/networking.k8s.io/ingress_v1.json
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app rook-dashboard-tailscale
  namespace: rook-ceph
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    tailscale.com/hostname: rook-dashboard
    tailscale.com/force-reconcile: "2"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - rook-dashboard.rya-bebop.ts.net
  rules:
    - host: rook-dashboard.rya-bebop.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rook-ceph-mgr-dashboard
                port:
                  number: 8443
