# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kellnr-rgw-keys
    namespace: rook-ceph
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:ZqwmrpCOS1rEtRWpC9HT9RccSKA=,iv:DeYJuh91BpMcJ8DRy7ZPRTpMGHXDXPhdXWfMxJiEwvg=,tag:bO4G37fWMWuAUFfWF7KayA==,type:str]
    secret-key: ENC[AES256_GCM,data:McuhWx97TAu4OQ1DHUQ0+15vNMtpiufQDP76qaukhkLvuhs1XRGCMA==,iv:BGkJh7bp/rk0Ss98iHCMd/eYXk/1i1rDwLio5szMRHk=,tag:Xiyp0aPbuo20jkbBZWd7fg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWFFFakI4NUs2bzBZaUNm
            ekM4NjJSbVc0L0lBak44Yk5NNjR6c1hycHhVCnNQSlRJdTYrTUh2Yk5mQ3hqNENl
            Ry9XcmRZM01ZODdsUmh2eU93cHRYR00KLS0tIHdsNzdER1NiRUZSRSs3WlMrcW9D
            NDI2aXBxVWZjSFErUXVRZFNjT0FkZ2cKovFXW1E0HBZ7WTel8zpmEATyiDGkGJFn
            ZhKLnju6XgNJ9650cRQKE1AJLydwsRKysgmtGMac76AWjZvBkXC/wQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T16:07:45Z"
    mac: ENC[AES256_GCM,data:qALOfYpKVv0uS7fScKUUdjhV8Bg/hg48X6Pvbjk7IQGtM660mfWWQYBrUgEB5uWRnFImbjpwf+eHlJQKUoIpw8PZwGo+cuYlKjfI77ysGCMSwiwupBp17FulS4REFMwcF/klpJ2a2YTDxCfK3jZGvLUeA4ARYggYMsesdOYGAPU=,iv:OnH15Ylu0kG5mQxLdnR0zivWVkbHneyYMXeJIUPHb2A=,tag:GxIQ5rv1VKebz9YDDTJauQ==,type:str]
    version: 3.13.3
