# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kellnr-admin-secret
    namespace: kellnr
type: Opaque
stringData:
    #ENC[AES256_GCM,data:hcMQk/5K,iv:ANYUezhaIWYXd4+x+dFrTN1KOIL39DDmIiHuqKCfYvA=,tag:t+YscOy//HbIoWzKI5p7+w==,type:comment]
    KELLNR_SETUP__ADMIN_PWD: ENC[AES256_GCM,data:Eb7VOQbhecVX/brj7+kjs8Dv38n/r1c=,iv:ahxaIkA5wvN/A69CSWcdNuyn0ccxDp4QTlFoQW19eMw=,tag:OKOSEMoi4isQvJqnlKpfCw==,type:str]
    KELLNR_SETUP__ADMIN_TOKEN: ENC[AES256_GCM,data:eCLhFFYWAcVVsaCGnTTDHnQi5+eE1SN8DFYYOreF/zaJ,iv:DIxrDBoKBK0Aogfjfe5/UJkZxyjyXx5b5MrgH+YTlOA=,tag:kDdGuqJBnwvJqBxTusYXfw==,type:str]
    #ENC[AES256_GCM,data:9puppiIl,iv:i+GUGLO55xQunbUI4aRjBd4zvmABeqDXmUi85Dc57Cg=,tag:bKi+zYbmCKnVV6s11GVnnw==,type:comment]
    KELLNR_LOCAL__IP: ENC[AES256_GCM,data:RIBFiPZ6JQ==,iv:IwT3Q5G6rL09XEwG6/CfzwiSlPIMQFDteS8nczQC3HI=,tag:Xwb7Enso6mJiWhXEbGSIVQ==,type:str]
    KELLNR_LOCAL__PORT: ENC[AES256_GCM,data:ez3ZXA==,iv:a1vyG+PaPQZKnoCoJBAWIVULv+yG5rKZpcsUJu/MEaE=,tag:fTKHbIfuy3flFfPDXz3Xkw==,type:str]
    #ENC[AES256_GCM,data:EFu3/82ipA==,iv:HwdcQTQKOYEPpdh3mXqgcwuhzYvHNPNJVKC5xwnnEj0=,tag:QeYznyLQvQHPtpKNctMeEg==,type:comment]
    KELLNR_ORIGIN__HOSTNAME: ENC[AES256_GCM,data:FnP9xrZG+gZGxM/z0IzWFZl331TSXllIrkBn,iv:ECdS9HpLjxzn/0Kik1D0VjpWXP/ToA3t9jHm3aIkvUk=,tag:u7yKyO4C4rFU9KvTEoKkvw==,type:str]
    KELLNR_ORIGIN__PORT: ENC[AES256_GCM,data:0Ar3,iv:7H4EG4j7VjMQTbF2F3Vd9tlrblDxtuLNm1XvvkUNzJE=,tag:rg0l0queAYUKx6aMyGOPxA==,type:str]
    KELLNR_ORIGIN__PROTOCOL: ENC[AES256_GCM,data:gfgFN80=,iv:vJj++un2Rj9WWzCRr5rpEXAl7qwhYexA8IpGzlhn7pU=,tag:n8fa2/bwZWW4h/fryzGi4w==,type:str]
    #ENC[AES256_GCM,data:DmjSIHcYT8d6,iv:OjAL6FTeLztlz7C7/GjG54dUptLMFV6OhjmnsK9ifpk=,tag:MDeIcXaDZcMiLXuC9Kz5Eg==,type:comment]
    KELLNR_REGISTRY__AUTH_REQUIRED: ENC[AES256_GCM,data:wht6XQ==,iv:SfEmNgGOutr1/W1Yyot2MffP173FFP8GccJVFUb757c=,tag:a8uY67MazfIPt4maHfUTdA==,type:str]
    KELLNR_REGISTRY__DATA_DIR: ENC[AES256_GCM,data:b6Oj28/zKvDHzTbDXa+U,iv:IGarZ35xAZPhwHn6Z1s0jJIWapB5cW+Ks/sJZ3Dif+U=,tag:Eva17pl3bjT8FN2BtFUHDQ==,type:str]
    KELLNR_REGISTRY__MAX_CRATE_SIZE: ENC[AES256_GCM,data:GW4=,iv:e1SkIApoerpQ1P6l1vcNSeUqwlmuEue0skv60cgXDf0=,tag:TGonG8iRAZtbyZdPPKehvg==,type:str]
    #ENC[AES256_GCM,data:P2La9Eo=,iv:d5K/DfIPQ8gA7NpjfdeNjkMU2Rn0SjZf5DmOklwN9/g=,tag:ghJHi2BM3Fml+bPrlIsq9Q==,type:comment]
    KELLNR_DOCS__ENABLED: ENC[AES256_GCM,data:7VdLBQ==,iv:Twx1M00/iXg/llSo6RhpQxWLbTBUh989XAj+wMZF3dQ=,tag:lVlWybpKbCGQVXCNWeVOUw==,type:str]
    KELLNR_DOCS__MAX_SIZE: ENC[AES256_GCM,data:P5vJ,iv:oEKm1N5xLkkngtx0EkIZteNs8Cw6RHU2emLCNNcyNxA=,tag:qatzxt0NO8qhmYLPCGDI8A==,type:str]
    #ENC[AES256_GCM,data:phJwrybW,iv:4WHpJe+Edaan1SsYd6td2K/IMUmLFKu6ZbK47+gFjk4=,tag:KJ90go2yWXVWBDuZOeyfEQ==,type:comment]
    KELLNR_PROXY__ENABLED: ENC[AES256_GCM,data:QPHSgA==,iv:Q+H/7Asn0QMuZ8z0PTTGGfp93F/gogQ5ZtsFFxs3UvQ=,tag:wm0uJjK68jO6oTzd7aaogw==,type:str]
    KELLNR_PROXY__NUM_THREADS: ENC[AES256_GCM,data:uYc=,iv:OdSrHy78m03TUj0XvWuxacVRm2h7Len9HrAkL8bUuKE=,tag:dI3n/6u2zbh0Un6te2BSGQ==,type:str]
    #ENC[AES256_GCM,data:Yb3hANaYk6oWJg==,iv:CtWXe1QQCQaQyFHcAsIiVgVt9M3qttU34xazTJ0KCbk=,tag:UMgzMmoNJA1W+e/BBXCT9Q==,type:comment]
    KELLNR_TOOLCHAIN__ENABLED: ENC[AES256_GCM,data:Uky9Xnc=,iv:LZWWhoz/ffH+LVQBmpT8AT+PKGInSlQqXC6gFS1BdkE=,tag:82K2YMW0uX7Dbzub1Pq0Pw==,type:str]
    KELLNR_TOOLCHAIN__MAX_SIZE: ENC[AES256_GCM,data:Nsbc,iv:fSujyEerBpkmPnAKuh6dHzEGH3PxgxnFlP8CrVIufrQ=,tag:TEjWyoKPPtQomlpw8dG2mQ==,type:str]
    #ENC[AES256_GCM,data:BwZ1b7w5edscAVA=,iv:d3/cAJdr4pDFySREHJKnyhgSj25WjTHAtmLaGjFjR1g=,tag:kywGOe+UTdOkfb5u/iWX/A==,type:comment]
    KELLNR_POSTGRESQL__ENABLED: ENC[AES256_GCM,data:M16ndA==,iv:kncRPDaeXaX5gMLZUbhvPZ3Bh7BfI4v4NUnbLYcgRGs=,tag:5esdGNzo2tH2USsgw8DtcQ==,type:str]
    KELLNR_POSTGRESQL__ADDRESS: ENC[AES256_GCM,data:FCzsa1QvP7wW7HeU2rvIZupGfB4uwcbg00ojB8ZPygqw9Kxwx1o7DIWbMhI=,iv:TQkudztX2VswwbauLRyyY5aGtk/ZHYZTlW6wlMBbc4s=,tag:PfauZ9mrhpHPwCORxEMjMQ==,type:str]
    KELLNR_POSTGRESQL__PORT: ENC[AES256_GCM,data:HbDn4w==,iv:fRUUXFJb68ud0AVeV7QsmyWJBhIB6LnI8YUsG+Gxt08=,tag:tb3xtNulh9WpuVMui5iZRQ==,type:str]
    KELLNR_POSTGRESQL__DB: ENC[AES256_GCM,data:JJIA,iv:uL0BRRbPy6rVq6LUdJ+lRtwujjo9Po7nxUVIzZ9hNyc=,tag:Jj+1EBPiQa62BUCRJsfN4w==,type:str]
    KELLNR_POSTGRESQL__USER: ENC[AES256_GCM,data:OP0tSjT2,iv:dSYo5Op/KCkhw5jvXiqCrZ1Ug2S/wbNuQfa81obCtMU=,tag:y6zfXyKBL4roQI9CvHFg3w==,type:str]
    #ENC[AES256_GCM,data:X26t,iv:+HgAWZHkSYe4T0+lPoKlShJEVN/VQqXDdHdMQ6JN2bc=,tag:m1JVjVMj0A3v2GCBOvTorg==,type:comment]
    KELLNR_S3__ENABLED: ENC[AES256_GCM,data:eEux6w==,iv:zr5fneVDMnI0Nv3bEmt3Nio6ptzFTVuPE78Je96lkmM=,tag:BY9kS/+s0XePRmIsI2BYaA==,type:str]
    KELLNR_S3__ENDPOINT: ENC[AES256_GCM,data:1nUyjQaQ+0GQCmJQykEpEKS33dLRJqWFWXTDphzeup0ytUkaJdmlzzGSllcgHfj7+Hy/4lZJ,iv:1EZe2bUenc6AmAXZ8lhqkuYm4bHSNJutYVrOE60YCw0=,tag:YgR4Xnv+4rLqBF24qIdibg==,type:str]
    KELLNR_S3__REGION: ENC[AES256_GCM,data:RRVErc0pFXRk,iv:hi8/YBHtQStKJZzIUBr2waWtOxZs71ATf2Y++O6x4Iw=,tag:2tlBrt+49kP45Oea2fc6lg==,type:str]
    KELLNR_S3__ALLOW_HTTP: ENC[AES256_GCM,data:qQHH8A==,iv:ucCVVt8sZgrvjbtX4BdMaCM0+epHwtVSzbp4AncBWgE=,tag:Ojjzt/yCKM0iVsWszoXX7w==,type:str]
    KELLNR_S3__ACCESS_KEY: ENC[AES256_GCM,data:3PxNN53LfIAYYIFP4s1kAF/1YWs=,iv:icG+5KJIkdKruD6VuH02T2On5CRhKNjNK0ftJfmhPGQ=,tag:XtncTg9vRbAef/3BqG477Q==,type:str]
    KELLNR_S3__SECRET_KEY: ENC[AES256_GCM,data:iqo1DXZCpienEVPas9bjTSABTkyaaJvLKgsbr9NVIVKZCjM+mH7ykg==,iv:Ws5BNux4wFlQYeVY9TbEcOLzlVDIjH2KkS/gOHVkL/U=,tag:SYv5AZyIIrZUvXXNUPnwdw==,type:str]
    KELLNR_S3__CRATES_BUCKET: ENC[AES256_GCM,data:FKgZ0rvclxA25rEuIA==,iv:OX9D0EgHW1FnwNETo9ylsdnftBZ4IJx4UrF8LRaz3sk=,tag:4rAcSAkGLnusLh+sNeX6RA==,type:str]
    KELLNR_S3__CRATESIO_BUCKET: ENC[AES256_GCM,data:n3i7BZX/tTe1q+v9jcjC,iv:fPwKPM20O8in+zVL48h8VwmgeGFrcqAWojz3Xl/RkAw=,tag:qP2F+kUBGAmn8DvkRb15Dg==,type:str]
    KELLNR_S3__TOOLCHAIN_BUCKET: ENC[AES256_GCM,data:bVPLldQ19TKh2M96FNeEyg==,iv:C9IEafgkklvsF1XrWZgwCZZs5FlivWXAd3r64ALcIus=,tag:MAilzmHYoGvpUJT6USmzvQ==,type:str]
    #ENC[AES256_GCM,data:AyGqGShuUg==,iv:dg4yX12syOuDnjoZffWb5hv+y5ItC25CMIxnSIiRxTk=,tag:2SquZ5hKkcw3NNlMRNcSMw==,type:comment]
    KELLNR_OAUTH2__ENABLED: ENC[AES256_GCM,data:ULNFTA==,iv:uKoTOljU5O+hHLT7s6CNifsl/eixlzLsk7jdsOezSvk=,tag:7omkunlhB2NMMsNfeB2PHw==,type:str]
    KELLNR_OAUTH2__ISSUER_URL: ENC[AES256_GCM,data:bIDNWPintIc95fsBoPqveQd108mB+D4+bzgIENF5XO++uNpwTc5M4pABs2/sOiZH3W2rYc465w==,iv:Hus85ZA5sGCF4BkrCTYVXwvaulTxBf+PNrEFq+RAn4w=,tag:1DlctgmrhhYNZxr28x658w==,type:str]
    KELLNR_OAUTH2__CLIENT_ID: ENC[AES256_GCM,data:Qmxqf9baR8srwEVfC/LrYEB3EFIYL9IGn/7Q4RYru1WTR8vTcLOYqw==,iv:Xt7e+72ZdAKnEhxg7cLKrq58bjbXwqh19X5FcR+zC1Y=,tag:6R/u/AppGrvw0GSxt12bvg==,type:str]
    KELLNR_OAUTH2__SCOPES: ENC[AES256_GCM,data:Ca/AXqWaNsx7coeqGdteWNxNm28=,iv:M7UWmRQsvuN5SOza3D1W6CbHZC3+FpbqkNkut8Sfiks=,tag:co9QRZP2H9Tb4xk5JbucLw==,type:str]
    KELLNR_OAUTH2__AUTO_PROVISION_USERS: ENC[AES256_GCM,data:YMz7rg==,iv:Sby47tVQc5mo4REx5wuzX8v++cMQJ+c76Gyonn9zqK4=,tag:8Tf/HLtPsLWrxauBKI57tQ==,type:str]
    KELLNR_OAUTH2__ADMIN_GROUP_CLAIM: ENC[AES256_GCM,data:wjA2q4Na,iv:q1x69y31R5zXp0f1JBL3oyZFUTnyMxFYb6m2+rv+5pk=,tag:9TrfL5B1tfLvGwxzR7tzbg==,type:str]
    KELLNR_OAUTH2__ADMIN_GROUP_VALUE: ENC[AES256_GCM,data:UAvXzSWRND/D/E4/og==,iv:1HZevu1Xa6MnOCsg2Wfnhb3simzFSrb+LFs5ykv6V+w=,tag:rATvexpGm+7w44CNWJqFXA==,type:str]
    KELLNR_OAUTH2__BUTTON_TEXT: ENC[AES256_GCM,data:4m2hvhj/fb00jDe2abOJqcjeGkg=,iv:f/zKU3rBAiOIHALYjhzQ9DphCfZvSAjbfMIw6euFIwk=,tag:qDhpbFoh8Cu+hMooQN1WTA==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUTY3enU1dlRFNmFzWDYv
            WHZYTkx1em1ObXhmZFlyNFlwY2RJcEYxNzI0Ci9ZTXU3WEs3elhvWG5wSjQxMlJn
            UEVsWlpMcWtDa2E3d05mdG5hTlZqQ3cKLS0tIG1JZzVyalZvTVRGU0lCV2JUZkFJ
            bHlRNGd0Y3V2R0ZUUXZTTEM1NEQ5NVEKdk9Uq06SCScgOwCUpMDrlnL7k4z3KHPy
            Hbsvxl9RG08WeMRm6YMX+fFHEz/a5ZuUe01Nfw3p+RWkNCD++gBGTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T01:57:09Z"
    mac: ENC[AES256_GCM,data:FuwIUifQc65E4uu9znXYnSXeJ9j7OIcStDMKqmcwRwLSf6Qs8xMtfkEZNfAYftL2YZ36CPVZHHBowghXgIkbVuZVZ4rmNdroKyABDQlMeLosaltNJfa/wlvaU553FoMAQTgBDCB0zACiA3JmCJtKDwgiTnsEX8PSenpk0CLJvzA=,iv:6L1qxJqzj9fDC1ykrJRcflKAd/rV8tHIS2ma08YkF0o=,tag:/N0kL+i3ktxw917PUgC85w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
