# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kellnr-admin-secret
    namespace: kellnr
type: Opaque
stringData:
    #ENC[AES256_GCM,data:dXouDxOr,iv:NahwFOYDTKJ+Oa6b1UYHuwi04Zn569fj6uOZT++koT0=,tag:43LbltKnRRHLvVFzsHljtg==,type:comment]
    KELLNR_SETUP__ADMIN_PWD: ENC[AES256_GCM,data:zqJ9gX7GU6Ho8q+XyM4zsVbxPxaKfnDEvUP6O3Y+nC0=,iv:yrSeGGuIHV3k9P8YzwMVEukhzzdTaDaZbFJIk635k2Y=,tag:pQUVkq463sNtr0thcMXLEw==,type:str]
    KELLNR_SETUP__ADMIN_TOKEN: ENC[AES256_GCM,data:J+d9w6aOo1x1nm8BcMbZE3JqMyDx2RQlJPjp0Z+/Wgw=,iv:u5ZyyxWqk0oFP26mezPUUQIKNN9X27Bwh90yMqxmpso=,tag:K4TVbncSjINKhB4f1x5RPQ==,type:str]
    #ENC[AES256_GCM,data:gMoVrMr4,iv:HYsbOOKveb2QLFHaJLOH4XVGMyoNJ0D2Ih1rGLvdkD8=,tag:MNXrL2zxFJGzoo3hZI1H6A==,type:comment]
    KELLNR_LOCAL__IP: ENC[AES256_GCM,data:sD+/YlK3yg==,iv:/anI7YivXNuYvbIhJAK1+chLYW2Mtuan31lQg+tnoRk=,tag:wL6DxgPaSY4r936DWRLqaQ==,type:str]
    KELLNR_LOCAL__PORT: ENC[AES256_GCM,data:6Rz52Q==,iv:ergEcwsMQWughHOeoVXQ/x/EXadIdtYTw1QOpYYk1/U=,tag:F/gjgeHOI3CVdEuQFx/Jow==,type:str]
    #ENC[AES256_GCM,data:wEInYExv+A==,iv:XXrAWh2kk9AfLzdliJmnqEUaQ+9atFTcvF7rZbdhOQg=,tag:xNCV5mSA5OCsTAntJdIfxg==,type:comment]
    KELLNR_ORIGIN__HOSTNAME: ENC[AES256_GCM,data:jebSVrtDPjPw5jjRX84Gb9lQYghLBJzeRX6U,iv:qbUWq//VFIdpIfn2bEDWlr4I90rsmsBVX8C0kvENkPQ=,tag:4Y+SripBXquMkEYbhBA2+Q==,type:str]
    KELLNR_ORIGIN__PORT: ENC[AES256_GCM,data:GA6w,iv:B1XSn1ngFaZaJ9aoYe8RYfAd7oj3klf0VMJ11bxitcM=,tag:U+LrEwodrezHI4FgYgMjmQ==,type:str]
    KELLNR_ORIGIN__PROTOCOL: ENC[AES256_GCM,data:07dZiTA=,iv:Be9u6wDiywvI1BNiPMAWF8zhY130xM3uhfa0G/HeFNs=,tag:y+uF0sExztruyZ5KZ02J/w==,type:str]
    #ENC[AES256_GCM,data:+fiLp5KkB8t3,iv:XR08gBsx7ALGOwBJe5woEg3DucFVAXl9Oqgb/f7LvVo=,tag:5PYZ7ISvR7rWsAglZgpiow==,type:comment]
    KELLNR_REGISTRY__AUTH_REQUIRED: ENC[AES256_GCM,data:NpHvmg==,iv:lKPEakhhDFGOzXe9syNZvxPZuNrduYqzczPOa4RrR8A=,tag:6CDJvHfH7D7TO/D67m6ndQ==,type:str]
    KELLNR_REGISTRY__DATA_DIR: ENC[AES256_GCM,data:4DC+aaKcYPCc7jbFbKXF,iv:trQQTfFoD6g266eGkglsfl1KP37yoHkGHkMfFi7nLHs=,tag:SxczDYQ6e9UgEugqrtD8Qg==,type:str]
    KELLNR_REGISTRY__MAX_CRATE_SIZE: ENC[AES256_GCM,data:8cc=,iv:yzCIQ+5UDzCDU0pDEEoeHcyuyc2FgtwrttnHfTOY1Io=,tag:4FCfj8Y9CQAb/flsy8jwOQ==,type:str]
    #ENC[AES256_GCM,data:9BMgBLg=,iv:ByYy/3Fiaef3EQJkGhdwCu8c3wjRSTncXh0J+6pEB+Y=,tag:5MRCL7RSiu+Tx71ezwBRMQ==,type:comment]
    KELLNR_DOCS__ENABLED: ENC[AES256_GCM,data:/6TdQw==,iv:08Hk6k6G7fjySQso0z69JzNM+KuMTVlV2/AcAOttObQ=,tag:x1pJR/eqKaYAduBm72y6zg==,type:str]
    KELLNR_DOCS__MAX_SIZE: ENC[AES256_GCM,data:aAYU,iv:QtDFPUQdxVX/ioPxGCBKiLxsogaGwpz1UYTAD+1whkM=,tag:eLsHvE0LuDSqU2KYWyJ2Ww==,type:str]
    #ENC[AES256_GCM,data:UC4S/WJd,iv:bBbemXDqyyyKTLltla0xSopP0lRk5eXrqKH014lQgCo=,tag:OPwhtfu+0UlYg3VCR2mSeQ==,type:comment]
    KELLNR_PROXY__ENABLED: ENC[AES256_GCM,data:riVwwg==,iv:+V5dBhjfewEaM+Hg9DYyNT3jabkXW4VyZ6vvS2Kc1Hk=,tag:Bn4k5/9QfSLpiM3Ctsp5pg==,type:str]
    KELLNR_PROXY__NUM_THREADS: ENC[AES256_GCM,data:ncE=,iv:6MSGdCjeTXfm3ZqnYaiADIX3ZhnGJC38jB0vUFFFreo=,tag:OFjhcB3qPGETxfNLfqCmQg==,type:str]
    #ENC[AES256_GCM,data:tiaO0okivfmzDw==,iv:gTM1xtu/ohgJBGJWUP3WzQueGjZMpXpOh9VvDAl3OSc=,tag:wPTl1D1yCFqA7shTYuWRgQ==,type:comment]
    KELLNR_TOOLCHAIN__ENABLED: ENC[AES256_GCM,data:pFEUkxQ=,iv:YpEMjO4D5W31jA2Y30+b/6j/t9XE8SK8yHASnflqauU=,tag:vD5Ir0zWJl0SWwlVW33LxA==,type:str]
    KELLNR_TOOLCHAIN__MAX_SIZE: ENC[AES256_GCM,data:lBdg,iv:KaRupZpYwZ1G3FtnwZEiuppWlIvWyiJEpWcyXZqGNK0=,tag:nc1wLWP4vKDi0vwdSaSgcg==,type:str]
    #ENC[AES256_GCM,data:jrk/S51jcy6SYzU=,iv:4HbANKVc58xT2F2RSoOgAHiXevgnLtXDJt3S9dR1tyY=,tag:pkQYd2qvxEdkGtmuRNyjTg==,type:comment]
    KELLNR_POSTGRESQL__ENABLED: ENC[AES256_GCM,data:IKXBBA==,iv:9QpRxbkGT57BYrcKrFaJ6LiNimEurc/JrqfY2HPtHfY=,tag:JlmBOJ7y9udQUoisfboo8A==,type:str]
    KELLNR_POSTGRESQL__ADDRESS: ENC[AES256_GCM,data:fpusYEUcqE01oVlEvCEvohr/fYMuP4URDwqkQog8y9FpO0+sK5em8UcEO6k=,iv:u8XOX6/+pYhsa8sca8JzK2TnqUA29mtlLv8Bysj1VqI=,tag:F4JPAB7SMFuAdn9PVpHkTQ==,type:str]
    KELLNR_POSTGRESQL__PORT: ENC[AES256_GCM,data:plkfTA==,iv:88uEpt4eIohxCBaE2ohbyy6PVIQyDoSE/+JidiDwwhY=,tag:sKywwLQgzM8yutHd7fcv5A==,type:str]
    KELLNR_POSTGRESQL__DB: ENC[AES256_GCM,data:BjxD,iv:bg/5T/zXiqfZzRAg2kXskQFZylzGcJGzn8lCUhwR4a0=,tag:b4Ps2FmepP/6Hl0CoV6RiA==,type:str]
    KELLNR_POSTGRESQL__USER: ENC[AES256_GCM,data:KO7RIrJN,iv:XcHtBKGJ6gpA/TkWsFLER6o04/DLBdfGDIdX3CvCsfs=,tag:TGzCMkRx6QSW6/oejdNvpQ==,type:str]
    #ENC[AES256_GCM,data:r9/y,iv:mk2gZusRGK3vjVgvmh4BltlHPjW0gu8m5i5aFLva49M=,tag:pZqFHE5OkEcSPCqMyZhWKA==,type:comment]
    KELLNR_S3__ENABLED: ENC[AES256_GCM,data:2GYRcg==,iv:hP7z7kI4+LdsHao6cbsaNUJrFibz7shbpASGpbNvko0=,tag:BS7/9RKyvIVPTjLV52WKCw==,type:str]
    KELLNR_S3__ENDPOINT: ENC[AES256_GCM,data:GCrPvN86iigSS/0Vv595QhMxwHq9Blf9D1Alokpju0KKMdLaOOCrWFncOlZo0wLoSjpk0pmG,iv:jmtQZY5y8QdCpeBTz1lMYak0CcxdaOxDTgmdI4Jv0j8=,tag:RhIgb/N0fQe06iZbH4yeQw==,type:str]
    KELLNR_S3__REGION: ENC[AES256_GCM,data:Wbx3J0Gi55/S,iv:3rjfCpxHOw0fa+ZfZYKSFsSo0J9hSou4GTx5G+vkOAI=,tag:P+VxA5GBcL8nQWILMI9nNw==,type:str]
    KELLNR_S3__ALLOW_HTTP: ENC[AES256_GCM,data:pv/gew==,iv:GxyOdmS+X+AgBVp1uYD0GiTr0DkUziFhSUMVa1fGhmU=,tag:FNKQe8Uqd6D3hWsMLUcbBw==,type:str]
    KELLNR_S3__ACCESS_KEY: ENC[AES256_GCM,data:P5olFpqVpZpikvvfzK2OONCbqy8=,iv:JnV4F3J4wD0SF7rT4R/QYRpNMBSyOPyaYMkWClHSTKE=,tag:krhGZWEKAI7gQRxGP/tbJA==,type:str]
    KELLNR_S3__SECRET_KEY: ENC[AES256_GCM,data:BmHtWxy7Zelrexx/eodfBbNoMyRgUu436RsVV98m0D9e9RVc7bo+Zg==,iv:By4Td/wg4FflpZvw6wGxITxrAw8iS42g9Ey8wg73uck=,tag:u6UEw+CjF978eUu9aQDp5Q==,type:str]
    KELLNR_S3__CRATES_BUCKET: ENC[AES256_GCM,data:A7EneN3o1Ahp669aBA==,iv:6VI2GZ3DOnGiA0668lYgfEX+XnCUmBriap/pqeJQKiw=,tag:ubJ4Gp76rh0b4AFqn4YsNg==,type:str]
    KELLNR_S3__CRATESIO_BUCKET: ENC[AES256_GCM,data:Xjj2rrh1dnKxq7kAbpLU,iv:M1A/z0UTx+qNwwOzAYZsphUR48Wg4/ZEEGuYYMw4mgE=,tag:bryn9WhwwyE9JmmEPQx3Gw==,type:str]
    KELLNR_S3__TOOLCHAIN_BUCKET: ENC[AES256_GCM,data:rQBubJskOGGc0us/b+3rdg==,iv:KwIS9QzeElLoBOokRiMQBAXs9FK1XMsv0wWVy+bo+YE=,tag:Ck70XPu/fvyrCmJEQzbWpA==,type:str]
    #ENC[AES256_GCM,data:P4t7yIDzBg==,iv:eH2Tk93hDHyMAD0/R93DvgjO1/1ZC8LilgdVrBKlCFI=,tag:QkxYi01t8JPiKibUx/VTZw==,type:comment]
    KELLNR_OAUTH2__ENABLED: ENC[AES256_GCM,data:v3vqIg==,iv:rh2iLYM+WrA0ogwKjfko/TCboTKDQ8fLjetS34MKpfY=,tag:UAk9dXo2wZT/dR2ZQ1ACPg==,type:str]
    KELLNR_OAUTH2__ISSUER_URL: ENC[AES256_GCM,data:OcAkk7qBaUCPvCuL+mmufK/QyylzZr13rq8hDxUiaXLASJsU1teXrvY4cv8kHbhFN0rMlHnozg==,iv:lRiS9w0axt98dZ56lbcngHm0uegL9V1t3sm2UC9ZL88=,tag:YJ7yNZNUrtleYtJTxfJbeg==,type:str]
    KELLNR_OAUTH2__CLIENT_ID: ENC[AES256_GCM,data:mpsFK9Jx2mz8oJ/ecC+8X3SxJxO4lXlBLxpM6AEMt7pQsy69432qVg==,iv:3iZBfOyIqcYt0Q96wFPrbLqtNEgz0fF38PdKHIFi4sI=,tag:LUtEgHs6nrrn2JmdcgRl/Q==,type:str]
    KELLNR_OAUTH2__SCOPES: ENC[AES256_GCM,data:TVLL5mMBMYjcRPBCd2xhD/KAaMM=,iv:2YWgGvItZCwfQGemWORt0XDgbsmoBLAJEjtqWU2dsTw=,tag:QbnjLCpPAvffUJlAcmcxZA==,type:str]
    KELLNR_OAUTH2__AUTO_PROVISION_USERS: ENC[AES256_GCM,data:yMA7jQ==,iv:NV4mAo+TzRGU3vPOc30kE8jUsttFDakgIw+IQsnacoI=,tag:LDwxZZPuu6UTCOkcCEJw4A==,type:str]
    KELLNR_OAUTH2__ADMIN_GROUP_CLAIM: ENC[AES256_GCM,data:lruMO3cN,iv:zCOrjnxBG/UfLAHy6CZRV7fRWmZPESM2aBdpOwOxJeg=,tag:7b3MMMW0znPs8DI1wY3alg==,type:str]
    KELLNR_OAUTH2__ADMIN_GROUP_VALUE: ENC[AES256_GCM,data:vWMiOLlU9/5e++x1PQ==,iv:JKW0Avat7yvpqVyZh73hXgRjJNTkScUMlmAQAmluhrc=,tag:RYZuLf8mjEzL2OZFDHZAIQ==,type:str]
    KELLNR_OAUTH2__BUTTON_TEXT: ENC[AES256_GCM,data:UQ0AE493OlWZ8jYWEINcGkrKnfA=,iv:Di55SgWn6e78DTqvhFRsCaHgR9ulPdO9YYi5ok0CTJA=,tag:ewzntCo3x/iggKXXOG1tIw==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TmlId0lzbCtWYUlHZ2t1
            YkNMZnhRMVdsWW9CQkl6blZ3RVlEQUxCRndjClM5Q1FtemlCWjFMMWNxQkpyTzY2
            cDdwKzRWWEIxU2lndTNoSW1ickpWK0UKLS0tIE9EWEI4MG50Szl4Q0YwRG1kdFRH
            QWdoMlFxMENEN09yYWZ0NzRmeEFEeE0KmLXPIXrf5sARsYqHHnxniTx9mFL7IteG
            8igwXoN1bHm29U6HuJCZuU7q4E1ZP/elxAK73orh5xluplCg3mJjBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T20:15:46Z"
    mac: ENC[AES256_GCM,data:UWBqp5zFb5Enf+tuohluPUoSk4hrqsBsS2IsNYnjCV3hUW2gUudZBkRhSb9XZEeM1UPV2gVsZdWNEahjr/ISdE8ccIeZLEnGAyBp73dVloqgvBxA83xJWGrmE+eyqc5xxR7zBaA95fpQ6ARUSFSO1O5QQ+qUGHAilimAzoY5c8s=,iv:Ww4Ire2pyvvaqptq2TXj5/Zt3fNziARij6YO54z7/FU=,tag:GtIU0pW67zNsbeZCZr6Onw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
