# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kellnr-oauth2-secret
    namespace: kellnr
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:w0+KpjulZw8cLVqWjowOgr5aTBCwoVaYOLpJOepY351AMxfh2uVSaw==,iv:JXPahR77DBBiQagCT2GKwHOfElk3SrnX2ALGvOfKfmY=,tag:ASBKttOsmmVZWUtvh8SlCg==,type:str]
    client-secret: ENC[AES256_GCM,data:xi8hMXuaEsrMh99a2JLBEwt7v/wbxL0TSKZmi8Scdidt/AqiOUUHAb6COqivRjWwuupYMX5k/+onEXfaF/z/T/HjyWB0JGs5FvC6PLcpdoFjmtOSoXaoAPBoyZZ6FtUGHpUnMlfQ8tiY8hIPIWK1IX3si7S8DhzJyiC1kgbV+Fg=,iv:MEUo4OYf0x0SgF/V6APRUOQK8zhp9r0ZLRaUIjRSsVc=,tag:djFg96pY+MMiB+GA54qzBQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZGhhNGsvWEFMU0tCTjhn
            bHM1Y1RYaDd1QWQ3bEZjWHRiV2h1cGtHS1ZrCnYyeWFrbjRwc0tIaHlpMi9JVmxU
            R0tLaFArMkJLMmlqTjYvUU00L0k1VTAKLS0tIEJTYTllbUFZcHV3S1hjbG5XaE5F
            WHo0THBwcEttMy96UldhUlRGZjVIbjQK/292LQ29BuyElJlXSRrP4teCjiG5iOcu
            O3S6ehdAyQlwLwyKei9InqqlMfW0jMIw2c6+WA5tjxwc0kUuLf3iEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T00:03:54Z"
    mac: ENC[AES256_GCM,data:FUICoSn0JuR80tkcZ6xpGj/c8k3w0R5OIKjZv1Y+MYjSGXckrVCsKyMGeNuiT6OjTE87sH9R4cSmw6WSeUFLULtWj57gVB6qWyiy2RO3z7pKMFad6celg05tQUPaaFgr4a7bGs+afFnpmXfAV/RHY5zsyv70pG2LSLI16DREtIo=,iv:pg1VqnzjYeAtWITI/g7EYvbQx7DlN8FezuFcZkbsoW0=,tag:8XFtRzlhw+wayK5gqpsSLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
