# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kellnr-s3-secret
    namespace: kellnr
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:G/UVmbmn8Pw6d4RCRs4QJSmK7T8=,iv:wG1BlZ1dsRQA1cMKFziE2UpJecVruIBkNkPZlcGj2UE=,tag:qRaUtxTy5/qqGrg8mehUjw==,type:str]
    secret-key: ENC[AES256_GCM,data:a1F9yPFxlam/lD28l4nkbW+Mlsvf6qikmFH3ZqSTryKE8g/Jv+rmNA==,iv:itloSeltLrkIGg9VA40zAkCw3pN79ZjCxt3IoLBKNtk=,tag:utJ8E2fAbmB4Lzye6z5ZQQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NjAvdHhJS1JqZFJmT2tn
            elcyano3M2xObjZIOGV6UUdyZGtLZkw2NFQ0CjBZeGlhcEwvZkMvVnFoNzlvdGM4
            WXlGa3NhSzhhc1VGRVI1dEgwTE9IZEEKLS0tIHZ6eW9PTXNKMCsrRFJIdmtueUtI
            eHIwSVNwNThuSnBZcFlCVThaL1FMMlEKEJ2iSucOzH22je4UYLS+4VrQsxKVK6xD
            EWB5prTe+WymcjzbLVsA6vwVMKl1HWdRdGI1ajJM03tHQQpMBfjJuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T00:01:21Z"
    mac: ENC[AES256_GCM,data:7dRQ2aE/m0fjab37VFeVHLepANu0WgwQsLB0OoPZiKZIyTo8BPjOESJagg6leXE/o+QFON9OG0NAGfU6xnVrv4XVmFUbOUAG9d/q+bLOxCwaJaNP5uCGv1DrW2vrKJfmxBvEdYsZeArqjJpm85gH3sxjuXlysLkTareoPzTL//c=,iv:M7sBsYMD7JpK7TIcT4YDKnuLHl7jr6HnYQfLVLcnbRs=,tag:o6wH+3a+5l4ZvcL06wqsCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
