# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kellnr-admin-secret
    namespace: kellnr
type: Opaque
stringData:
    #ENC[AES256_GCM,data:TszlQEaV,iv:T7bsUQjJlbqWIK+N8AwEZEiVJQ4RwZAZKFOvCYlyXRQ=,tag:Wy5iV/gLQ8A+nlRCw7ySnQ==,type:comment]
    KELLNR_SETUP__ADMIN_PWD: ENC[AES256_GCM,data:yahQP8IQeSK3Fc32c2qCrbb6qxWwA7NGEbvXt3otxr8=,iv:Q5RSlEmkiwXnbM7DuABN15hvolziwbfEhMwVVZm8rIY=,tag:71sRxtDiUepR0FpP5MJtmQ==,type:str]
    KELLNR_SETUP__ADMIN_TOKEN: ENC[AES256_GCM,data:49ABAOC1c/wi3a7ge0rgxDsdqAiAywSLM74SQ6+NAb4=,iv:9/oocxZ+0i7t3Hx3rm+d4k1FeegvQQL0fcDIbYrwr7U=,tag:9LB6pskQjGlqK+o5dCVhDg==,type:str]
    #ENC[AES256_GCM,data:ysDRnmSL,iv:2RyBCW/XvRfzUj7umOaVlAP9WQ700Dx+bn2jHQWkajg=,tag:wk6SDaSfK+frn10Jn8hQtA==,type:comment]
    KELLNR_LOCAL__IP: ENC[AES256_GCM,data:+TP8cmQJGA==,iv:RoXxKTb/nBCDFwdHJ4DOXd36NsUVicLvNd2bjb7aBgE=,tag:2AAZuO8uNBDz53CUVOLhRw==,type:str]
    KELLNR_LOCAL__PORT: ENC[AES256_GCM,data:tPi4KA==,iv:pOVK/msIpEP/LhGQrYypXuEMQ/LpD4Ti0DrJkekA96U=,tag:rtO/f6bASRpdhdguOiZ6EQ==,type:str]
    #ENC[AES256_GCM,data:1SMEWuce2g==,iv:pXR/KsuEvVo1xyQVzcQyopjQ1POem34trOtYXm2egik=,tag:W0VT2azAfEjZ1ufWBWg44Q==,type:comment]
    KELLNR_ORIGIN__HOSTNAME: ENC[AES256_GCM,data:y1HLIU5n3wqq70ciH9K/xRTioeQqh5mV8viR,iv:9W5pV0r06CnCU0GsTDmnVXuys6cUVWYek9sD5R0YQX0=,tag:x8xpbBs5fDF8kVjFKYoU8Q==,type:str]
    KELLNR_ORIGIN__PORT: ENC[AES256_GCM,data:dzSH,iv:mkiUz0hfUA0VA4Kwes52zpQ+445GwGLKoIXGdKW2XIY=,tag:LwGtMPwHQlaybcnYYH5MgA==,type:str]
    KELLNR_ORIGIN__PROTOCOL: ENC[AES256_GCM,data:+6I79IE=,iv:pUfz9ayBfdEmSejV2BjSkMKOGLVOtulUdoGN+8JtQjI=,tag:DDYrNN2NHFgckPJUy9OGxQ==,type:str]
    #ENC[AES256_GCM,data:DDOi17vTRT2K,iv:cz3Epd3hOdcw6CPiYaxkuw/zUreYYY6g1LN6EHrDM2Y=,tag:QhJ9KPB5DgQT+XgKyii4YQ==,type:comment]
    KELLNR_REGISTRY__AUTH_REQUIRED: ENC[AES256_GCM,data:HR+m5A==,iv:uA+YeuoG31SMHUzWJRTcSfz1TG2PDx+TmgTtFSnyBQE=,tag:lkQT9Knw7mqbnY+7cl0DIA==,type:str]
    KELLNR_REGISTRY__DATA_DIR: ENC[AES256_GCM,data:iDwWFZJWJe0ufE5XMCrL,iv:TcZtlSVQgrChbDXJaFC4ac7JcNB16sanHqFPehHeBpY=,tag:X9v11sLh0CiX25SjznCorw==,type:str]
    KELLNR_REGISTRY__MAX_CRATE_SIZE: ENC[AES256_GCM,data:J2w=,iv:RZXPwIuvl7nnVnnoYfFnZzTyRiMQJC6d59q+l42v95I=,tag:RXyE++thMFWBJu29XYRvdQ==,type:str]
    #ENC[AES256_GCM,data:gZufR94=,iv:7zrB7Q7eXxrOT2vdEI/qhRSrzXiuFce1VpJM9dp5/bk=,tag:f6sXZmbccv6R21MkdfoLSQ==,type:comment]
    KELLNR_DOCS__ENABLED: ENC[AES256_GCM,data:QRMEwQ==,iv:6Ne6hZEn8AGSLJwwFcCw9K+MMsHwfT4UO9yRuai/1D8=,tag:BI0kKYyaJaCTaooGsCx4QQ==,type:str]
    KELLNR_DOCS__MAX_SIZE: ENC[AES256_GCM,data:AKgo,iv:EjheZER4N0fUryKBgV7GXYrMRAlFEYi4BrVixW0/l2s=,tag:1uPgm3DZQjQJNIqGuQiwUA==,type:str]
    #ENC[AES256_GCM,data:lOUn31iC,iv:J/nYwYFCHkswER8vpTlfDg8oU3n5w9uGw022o4qktS8=,tag:PxiwvX/R6bKKvDwc3JqX7w==,type:comment]
    KELLNR_PROXY__ENABLED: ENC[AES256_GCM,data:54wFZg==,iv:xLGhO6nSwDyQ2zFrTjHUN2wwjNrk2nRkAlMIy5G0U3M=,tag:Cu5xXtVzvy55EMHULp6gwQ==,type:str]
    KELLNR_PROXY__NUM_THREADS: ENC[AES256_GCM,data:PjM=,iv:A57OcDj1ahrE65nHfirbZqp+6AjM7sqTMXJmICKWby8=,tag:wW0RU8mA3B6cRWH//DZpbg==,type:str]
    #ENC[AES256_GCM,data:5hQOUlGignE1+Q==,iv:arVdBe1ghCvE9J7k7jqo4VfzbsdFJ2BKWe0lq8ULN5M=,tag:hdP80I7aQLREJ2Kxe/l2gQ==,type:comment]
    KELLNR_TOOLCHAIN__ENABLED: ENC[AES256_GCM,data:Hptkoiw=,iv:un90W2najLW1FA04EA3YEyIoKFrBjcNsOyZQ9l+XvtQ=,tag:G6TzoCvq1eGKYcIGK8jSIA==,type:str]
    KELLNR_TOOLCHAIN__MAX_SIZE: ENC[AES256_GCM,data:2TRP,iv:hsa7EwR+2Spnsy5NH5jpUs/EGmwxsxr34+q5AfHG4ag=,tag:d5I10iisAW7m/73HJIhs4w==,type:str]
    #ENC[AES256_GCM,data:fQYvr+GA8Ulo9wo=,iv:XY9zPJQJg895Qvh83kuNm8XRF6EY+H/nJA1q3PdUehk=,tag:PuVfAQkuzRW3Y0WfgL1XXw==,type:comment]
    KELLNR_POSTGRESQL__ENABLED: ENC[AES256_GCM,data:Fk7Yiw==,iv:l+a30vs9qV4OoWZ5sYvVHehwWqZR2tTJ2UIXupv/3/s=,tag:Wu/q1kUQrED/F8P0i+j9jw==,type:str]
    KELLNR_POSTGRESQL__ADDRESS: ENC[AES256_GCM,data:yxZ+eYPP+9b5GuARK/ia70k6GMCkQCdc4Q1Q9kBpoAX51d81ruDnlNhli4g=,iv:J2XNuRNcOyW+sdIkFOHOHUeJl8i1ynOGwQSQH5RaQJQ=,tag:7vV4uovWJtwFU0IKSWxiJg==,type:str]
    KELLNR_POSTGRESQL__PORT: ENC[AES256_GCM,data:u26Gvw==,iv:2g3ypPevQFnRbno0gGdWWHL+C3k1YfsGG2fuLPfVN1w=,tag:ZRnPtO2GXAr6FNC9ONo8Jg==,type:str]
    KELLNR_POSTGRESQL__DB: ENC[AES256_GCM,data:XabL,iv:II5xku/4zoHpEY+tZqGDje8EB369JtPvcLgj7T8fVxo=,tag:qqbh4FRpLL1iJDKp03nQRg==,type:str]
    KELLNR_POSTGRESQL__USER: ENC[AES256_GCM,data:PKaARgTm,iv:SZKIT8yAJrSXTClYE1K59Mowz+Mj7Z1+kG9wfzz9QTw=,tag:BaqCVKfzTeb4ZiNKT4cJvQ==,type:str]
    #ENC[AES256_GCM,data:KIbq,iv:Y/2pMSBm6FkJhsgcNw12cm6ZzDR/JFPI4cgKpJYpr1k=,tag:3k73zPwTPbIQMHmZgiErhQ==,type:comment]
    KELLNR_S3__ENABLED: ENC[AES256_GCM,data:8dfDIQ==,iv:5GqLHv7ci5AqB8ye3Aq5p8+8nfWO96GTXg8y+mbxAnU=,tag:feKrUThNbiZjPuvftmwwzw==,type:str]
    KELLNR_S3__ENDPOINT: ENC[AES256_GCM,data:blkMNWC05+i2aZKtQd55G2fQLc7eL/EfWs9J10oZsOc3iJs5tLo/kfUGwOWAsykrNKn4wsWe,iv:U0dLZGR0E4yBtyp5cGNbAE6rtpVHAOuTdm1gP6LqmG4=,tag:oXjGrwnmnbI8Gb8CQQdM7A==,type:str]
    KELLNR_S3__REGION: ENC[AES256_GCM,data:/zrHrELm9JWx,iv:B3X1kn3TR+SI+uvAb6u95j1sIGpU7br6dOdCMFEw/F4=,tag:8pPjCWkw16zjaYK5/guR/g==,type:str]
    KELLNR_S3__ALLOW_HTTP: ENC[AES256_GCM,data:Q+HVug==,iv:5qm6PizrCwDEYaQv308FggZnB7ryQYHtL6URoJuD4V8=,tag:5I7gnO1hY+b8bvKjNGB0ww==,type:str]
    KELLNR_S3__ACCESS_KEY: ENC[AES256_GCM,data:14deiAiuAwRifIlnWF73btFLjxk=,iv:BWL18mjy63yM5D1k2Zw/T3ynMlG6EYGMytD9eXuu2eo=,tag:VzA35q534zMAJnIsE/sMzg==,type:str]
    KELLNR_S3__SECRET_KEY: ENC[AES256_GCM,data:OC62DA8YtKxGu2zqPa+/s0DK40wQew3jqRbERIVXY/Dj7vsq0bmQyw==,iv:bNMa9p3ribI3S289pPCJjG8ksgHGgnTLFxRreGJxNJQ=,tag:vB0yRPTpThJO4/8PFqa1nw==,type:str]
    KELLNR_S3__CRATES_BUCKET: ENC[AES256_GCM,data:bl502ePl73x0i+wqXQ==,iv:TkZERsTXCah7yEOMz00agp+dCbeg5uEunH96VYjRyVA=,tag:UURcq12CyqfbikJ0YK4sng==,type:str]
    KELLNR_S3__CRATESIO_BUCKET: ENC[AES256_GCM,data:+3HOg1iB9S4U4kMk3eQy,iv:btqHh7eDF26aEsIQ5v0tcaDy9qwmWeS/oLBQYYZ9lRw=,tag:t4MVnk3Bit6VbEJ2qV2+bw==,type:str]
    KELLNR_S3__TOOLCHAIN_BUCKET: ENC[AES256_GCM,data:G/QL93r1WT7lkHpc4pCiNA==,iv:ocxqs9BMoz18uNOYJIcJ1yGxpuY9/B+9K7L0AfF54cs=,tag:eueYc8Vyvkrw/IqaWmg6YA==,type:str]
    #ENC[AES256_GCM,data:sD5nDLN9Fg==,iv:l2LWguuFpTjVt7w4c4Ih1vvxr/PbdXIy3VEyQGshdyA=,tag:+6Ll97oburH3jG9MRw5O8A==,type:comment]
    KELLNR_OAUTH2__ENABLED: ENC[AES256_GCM,data:L0NOlw==,iv:SVA6459qCqPusF3s4fqc7Jm7dTem1E/W3PZTDpyE/pM=,tag:rBoWxT7oCCLiIKwr2tvKSw==,type:str]
    KELLNR_OAUTH2__ISSUER_URL: ENC[AES256_GCM,data:7yaggwJQ8bk/qUJnRw3l+MPLmmRIpWZ08hcTYd0Q5j6qRwWs/7KeQ0G+6HyURUdn3CNNIWEL,iv:NmE/7CBzxlWfIVm1RUJD729cRp03natyqzXJbLHmfvs=,tag:EQxDM32Y245KQVpD2oSMFg==,type:str]
    KELLNR_OAUTH2__CLIENT_ID: ENC[AES256_GCM,data:cGCPAZCO1Iu4fmskyagT1iCnARbSIk03jrN7Qf5Yxq8Dp5TIBdpHIA==,iv:Dvj7CfWuTp2+8ByaOOa/i8OVyjozOb4sdOnbtTjKSVs=,tag:G/xtTt7AL+A7kWoS4w+Igg==,type:str]
    KELLNR_OAUTH2__SCOPES: ENC[AES256_GCM,data:TgHLlKkItb8Ag4ZVpDZDDKAeehI=,iv:FIUcpfYBkIVBH5Jn4gAMgzrP+JPi5YNDkBpyb1+0Jso=,tag:Us7v7lcZp7tl6+az72Ct8A==,type:str]
    KELLNR_OAUTH2__AUTO_PROVISION_USERS: ENC[AES256_GCM,data:9vmGsQ==,iv:GC6rTo2ENZpc8gBmzWLS6mzBhuN/5sX9F9fddHvrxe0=,tag:5VA5qAXUIo72QBk5q1etFQ==,type:str]
    KELLNR_OAUTH2__ADMIN_GROUP_CLAIM: ENC[AES256_GCM,data:ICcXu/Mb,iv:RdUVT6AK+OoOF0ZliVXqvgY3/BlS1gk/B4Ilgt3oExI=,tag:VVqKpdrkSehHF0Trg/cmMQ==,type:str]
    KELLNR_OAUTH2__ADMIN_GROUP_VALUE: ENC[AES256_GCM,data:V+MuQlKeQBGqhkc2zw==,iv:uZ9nW/InIGoOkDYoWlFsnlllL0IiWvI5xfP1jnqWlx8=,tag:Rzi0QOySsDf87qbbQXkGPw==,type:str]
    KELLNR_OAUTH2__BUTTON_TEXT: ENC[AES256_GCM,data:wqsCFmCnj5Amh4PfyD9w9W7hvUA=,iv:InJ9bP3Ur3y4N8QTsJxZWAzas6H1St5oeaLmFW5BBts=,tag:uwK/CVbtUflrnDZNwSptZg==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOXhVZWp2REhSY2NhV3hq
            cVN3d3l3OTlDaW1iajR6YkRVemhFMkd6MncwCm5EaE5uUlZsVDNiSS8yS3BwanFX
            SG53REZQTmlmbzBEQ3MwK2ljNHczSFUKLS0tIDY2VFNoOXdIZnp6T2hDZHRXdkpF
            MWVJUkFhSGFISExnUTJyMmJKd08xaEUKzoigbXHFUNLUhCHpZG3xhqN88Zxgdmo2
            uz9eOpmj1Ksb1gROZ0xkVljR0K7rHt+m6O3JjwC+xbLd7CDKanOaXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T20:40:36Z"
    mac: ENC[AES256_GCM,data:Hf+bVkUKDJPHEeD3aWBAnHGUPg+uNRA4NC7nQR+ym96A8lpguH00crQ2J8gEuiTPhIX3en8FCD8RGpIFep7IpXtnLHSexPP0ngCmKJYm7bUWmzxw8ECigrgE3WWEL0u/4ElbaahuVgpJy97SVZNv9NS2XbuKJtLv8Uw/mCwl90Q=,iv:OTQ7J/t0U3JQuyJZHGy7khy7AjZ1trDahcw/C40EudA=,tag:8Z7cTzN85xgW78Tt0LAq4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
