# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:PzFqVgxP/zQ=,iv:1GGOh8ud3HuYUB7jb6GLZfMJvQnnE5ZWrppvm2SqyKU=,tag:L9ZQ/dEx+fMNsQOBdzAFGw==,type:str]
    password: ENC[AES256_GCM,data:JCHhONV0US/NCs2mz7VdfgYIOD3IbOT6kg==,iv:4W5/DIqraj4yUWjBqC5BJQJbbY7FZnMZD4Z0yKMzpY8=,tag:YChuw7P3OpA4FT4cTrZATA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTUZDOFBrbFpRM0p1ck82
            ekx6ZUV4R0ZvMzg0KzE4dUs2VU5lQUIzVFVzCk5YN2RReFBvS1BpVSt3OW5YYnRq
            NDNDQ1FuNkVBTzlPU1FzdW5mTTBrbWcKLS0tIHoxN2Zia1lnS21zbkxWcmlJYzVl
            K1JyUHRza0plYmJlRUt6UVh5b3ZtdVUKBRwRDVU7Tao9iB3XH88esiuRdrgGTms7
            fLqhtcHvz5s6tHqSFi+C5baqD/zvD0nHSeaIvKbCrYJTAUBUFCabNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T21:20:41Z"
    mac: ENC[AES256_GCM,data:0WztybvHccrwmGQ4W9W6wyT+N0sYw0hNWah9xH8H129by5x52Mppm0s5sIwfkqoimtzV1l8wq74W/M9OwxYiaje721CHXVU4CESCCpuHpypIl8VVl2KbJHB6x6LMVWCjyD4VdaAJi03sjItncV310co4alfvtQ1GyERd7ta8r9E=,iv:UH36bZTLrsBjPSiuGaRMBThS41fJDT6cWFr39TXhmGo=,tag:WOMdvWTRBkRK/mQ16WOyhQ==,type:str]
    version: 3.13.3
