# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
    namespace: gitea
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:CCPTc9qaxm4=,iv:iKTxVtoIffRssq1P4w4wbMqHnadLNX0jkKIt7wpEUlQ=,tag:wXfVqe87JE5TYqVvRwPaIQ==,type:str]
    password: ENC[AES256_GCM,data:9FmtvCK/iPuerWnpZCJDp0gnZAC2458ztt722ao9cry4+lZmpooTCg==,iv:Og3zU73J8KHa1Msmk/PzTaBWnhhmrNILlICe0UrgtV4=,tag:6UU+N2gNjPQR/rcR0AzKhw==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SnI0aDZNYTRzNzNiVUM3
            UCs1MWY5QzU4YzhuQWg0dTlyclphVUthTFV3Cmh3UEFFKzlCQ0l3UVZDNTNybGc2
            S010RHdOMkxXRCtPQ0RQamJFNFJaazgKLS0tIGFnbmIrbjJEbXF4ZWNhK1cwYVYz
            YnlUNkVtM2tPeGdDaHVZdGZUOWVjbm8Kx9fgxyvIivH0Bud+rM6uwHfl79NRHZVL
            R7GYMoFg7hf69oEYDA+sK85lcPtozs0DJ1O+ubJPqZarXQQ1VnsVuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T06:22:16Z"
    mac: ENC[AES256_GCM,data:2dp1TXbfTep+af4kADb7We/pJaBlZMoN3vXtpZXjSmy06Yax2pJLlvADrrLa7ZSONNAL1eMUdgLX3pGNFrmdRSFiSi13Dj4pr4y8PxfXeoyAySgmnQQ1yovgcdDvvBofANKfqM0sOlnsYzl9LObdoOntcci6bUJBQQ40pjGJHk8=,iv:KmHoxQV0vLwPpdLrxag5h3hO1HtTPtxxUZSv+bnQ//A=,tag:nk0asRz6TQtSFTNGr0jwug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
