# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: lakekeeper-db-user
    namespace: lakehouse
    labels:
        cnpg.io/reload: "true"
type: Opaque
stringData:
    postgresql-user: ENC[AES256_GCM,data:Yo30IXAYnnf8FQ==,iv:nT8Sg39XUChO1EvetK3TDMESsJsmZq6PDbOtIBybIEA=,tag:ECF7Gk+l9+GIS0zjMuGEew==,type:str]
    username: ENC[AES256_GCM,data:9oypOgsWK8UwOQ==,iv:OdRjsJug6rd4io37oEClrThs6bAH1ZyIAWjxF6YVri0=,tag:6ldz6zSY1VSib5NMfyIFQQ==,type:str]
    postgresql-password: ENC[AES256_GCM,data:/Cjf7/nE5RBVfMW1gHiC45EAfSFMDTHEUh+7b6klrSo=,iv:hklNi/mKm0dAzN4IXaBQ2AAMpcbzSJVAm0P5dNRCt8s=,tag:ZMCkpdAf9Y3x8XR+qi5fHQ==,type:str]
    password: ENC[AES256_GCM,data:x5AjOWjMUNGf1t8+c3BkqSpM6E/j/sYWXu2CrQZLCYA=,iv:tVYL7O4fqo9LxhY53Lba9KUGIHTYzLjd6EcnnWvfh3A=,tag:Vl1tvJhaEzKuPkMN+I1B5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSFhFb0doZG1CTW8yckEz
            V1drQ1l1WDNQdUZkd0s2SlJtdGVRRUpNRFZrCjNvb2lVczA0NEZ6WFlVSUVMeFMw
            czlhMUIvNnkrbjlFQlNZQkRoVDBJZEUKLS0tIEdxSWJ1VEN4cXJacHQ4M2VoSytq
            VlpOY1VwVkNxL3QvOFU5VGdEZ2kzdTAKdq+nB8rOafWMPEqUO9Cu/oc1H+qrMiJ2
            /+PWOewtI+V1e6MSc1OJshXFGndhhkQXo50xY3CCb+hxm3seZvbmkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T17:17:36Z"
    mac: ENC[AES256_GCM,data:CEwxRCzMHZOkJHOeWf13ztEWcrKUAgUhxtn9liFsNo92NjzrlsrPbxFxip6lGbFCW9CiZP/Sq2/X9Nw5Qt0dacj3sWLnxg/JzXjSWbspP+ZeWko04o5akruP1BzuJfMBlbRUiLZwWjJL50Y9mqS7UwE/8kvW4o8mE93vbrVXPeE=,iv:B4gE3d4/ySk6zSbHrbNbUKcfMoK0ZA1Y43WX1gbKZJU=,tag:pkL/qfHduENHWHZE9e27FA==,type:str]
    version: 3.13.3
