# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:mbKapj8V5N4=,iv:YosrGfG376eUfJhOIUvVFrxazuR6qpCtuAvFIHmZXmg=,tag:XJZCKUurjLqlnZ0TDD6LbA==,type:str]
    password: ENC[AES256_GCM,data:nm7eqIfEibzjmqGv3jvQDuA57quhI8sxTQ==,iv:EEOL9L563tsIuvBKACRADzhu9IBOc8nO/2GIrYKZXB8=,tag:nDH154DzjlQ0ovfaASrJ3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVTAyUEtKQVhOK3NMZDZl
            dm9LWkxxMVNONDQ1TkpvODBPa2N4Q3BLNmg4Ck9UTkRxcjNmelMxa1I0VDhmK0d1
            c3VreFRKdENjV1lkRWlvcmVVSUc2SzAKLS0tIG5TVW52SDdXQ2NwVDM1VTRNT0ND
            OVhiWStuNEIrZ1Rwb2x1V210SFMyZ2cKl6p3N59Spp4NVtSya+23CZy3Bk+UhG/I
            GBwJFv2Bf1JFz9wtAHMPzN397pP9L/ZGj/Y7WJLxz80Ny1eB514+5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T21:20:41Z"
    mac: ENC[AES256_GCM,data:IG4nvrhT0KEdBjTluB/Orc++lynfmhNIgdcZDtlU8SvVz6P6GrC3CEO7z/heGC7FHItdQH7KhrP9MFrg8L2/a16NUV2SauLSjoAbQc7rdTAGLtr9JS+ufZ9CJAaskCagqKbCuLiHRXMvhcwxsKxOQWIGaA63kBMeo2RsXkTuMf0=,iv:CqtRrkJIfO19d3lSw0MzTL1cWxsZIl+9g0tiVu5aV/I=,tag:0c0UvuKGLqv5TNVnn0SisQ==,type:str]
    version: 3.13.3
