# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
type: Opaque
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:n3OYTKeynsVDlI/nAhPIPV5hkA8=,iv:CPwT1Ex8QrWpaUMoQ4DuM7sxDUabYSEayFvKy0bFUZs=,tag:tXjk8HhRPo5eZLE6aAbDJQ==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:3P0zzit5o61ZJM2UTlGsE17AiEp74mBtIx8jtwgmBzFvU0j2fJKYMw==,iv:2IOEZYnpuWUsbCwR2fOLYEBfm/tnEOV758lAnCyuFDQ=,tag:M29qQviCttv40dXeqKTmKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRks2QjVsMkttV00vak01
            SGREOUQrSW5xaTlYbWRBdWlLcmlmYVJnUUQ4CjRXTzN2R2VKUnpIV0gyMjBpY29v
            M2s5T1M0dU92aCtjeWNOSXhpajRweGMKLS0tIEdsTHlVTy91aTd4NzlHOFVZdTcz
            QWZCSUE2UmM5T3k2U0N3bUh1VVo0a0kKvS/dblVAtZfwYUqPDj5yk/YMJ62bEiS/
            feX01xrEjTr2FOqSQQvYkc4DtMC+53f2fDkXvJ6kMSuGY+2Du/+tKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T01:07:46Z"
    mac: ENC[AES256_GCM,data:bU7ojCI/Iavt4SakZRwQZDHh0rrPhaiRuI96Af2CWlPZNT+ySf3ygzeLSLXkZ/Li3oGXiDHqBJkQ0iGdfDUxlWuyn4pLbQXZVQ2aVeyD4WFcJkFawtClN0Jw2efZcLK7eJHOfafMYL6b8vR3PEV+d5VLMqw9PPfxcWWEUQ/QA50=,iv:9DhPLDRKCaLEQJmuDIg9s0htdCCEhYdGCXQo6HlqQTc=,tag:yBKFnDMDZlmYhuEu7+MpBw==,type:str]
    version: 3.13.3
