# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &app immich-db
  namespace: immich
  labels:
    app.kubernetes.io/name: *app
spec:
  # renovate: datasource=docker depName=ghcr.io/tensorchord/cloudnative-vectorchord versioning=redhat
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.3.0
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi
  enableSuperuserAccess: true
  superuserSecret:
    name: immich-db-superuser
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
    shared_preload_libraries:
      - vchord.so
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
      - name: immich
        ensure: present
        comment: Immich
        login: true
        superuser: false
        passwordSecret:
          name: immich-db-user
        inRoles:
          - pg_monitor
          - pg_signal_backend
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      data:
        compression: gzip
      wal:
        compression: gzip
      destinationPath: s3://cloudnative-pg/
      endpointURL: http://minio-service.networking.svc.cluster.local:9768
      serverName: immich
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: aws-secret-access-key
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-user
