---
originRequest:
  http2Origin: true
ingress:
  - hostname: postgres.${SECRET_DOMAIN}
    service: tcp://postgres-db-pooler-rw.postgres.svc.cluster.local:5432
  - hostname: ${SECRET_DOMAIN}
    service: http://istio-ingressgateway.istio-ingress.svc.cluster.local:80
  - hostname: "*.${SECRET_DOMAIN}"
    service: http://istio-ingressgateway.istio-ingress.svc.cluster.local:80
  - service: http_status:404
