# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gravitino-db
  namespace: lakehouse
  labels:
    app.kubernetes.io/name: gravitino-db
spec:
  inheritedMetadata:
    labels:
      istio.io/dataplane-mode: "none"
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql versioning=redhat
  imageName: ghcr.io/cloudnative-pg/postgresql:16.9-22
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: ceph-nvme-block
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
  enableSuperuserAccess: true
  superuserSecret:
    name: gravitino-db-superuser
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: false
  managed:
    roles:
      - name: gravitino
        ensure: present
        comment: Gravitino
        login: true
        superuser: false
        passwordSecret:
          name: gravitino-db-user
        inRoles:
          - pg_monitor
          - pg_signal_backend
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store
        serverName: gravitino-v1
  bootstrap:
    initdb:
      database: gravitino
      owner: gravitino
      secret:
        name: gravitino-db-user
