# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: gitea-backup-secret
    namespace: gitea
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Pb1zsh6rGOSJu7oGS67nsXkbDXg=,iv:wFY/ZfhGAsRhvJ/LAa5cUFaLCS4GOsOzi2DWShxCj7w=,tag:U5xL+CuEudLpkeNympgO9g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8Z1IKlTNMFIfSZ1v7pntt+wIo0ArCZYEXkBY05uhsVLUuZ5QkKWtww==,iv:G6BHzuoeKGkDia0vNdXeAfUxwPkRXorrXytmegYTNF8=,tag:YwrvDtSPO8ATlT/5o3hl2Q==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:h7Ag1K0FZlOKThzMXGkOB0EDo5JbClcRIcMPNX8IB8oWLJi3wx7Ocz3Cwxt1JUwbSffAdqgD6F4opk8qMFVVPPgpXGCozBfHOcgPVjSdjOjnkHXe9ZqkELJC,iv:9mOk/F5gE4jX3BzVWB8izfK8Sa0xqO3VaE78JjQqkN0=,tag:2bH6uXYQJb14iBrUtAsIhg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:3wmr15QGS5e4s03v0eFQsO7bH3cM9TN10zd/CI4r7AKMlte7VSIRXmtwpJM=,iv:tWNcB5MENKumKMVVaqcGItoCffwWDBPGt1ydRavdcOI=,tag:uBpCGga5PvtSxFr9R+3SIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTldzRmtMRHVXekFvbXF0
            V1lXSVh0ZXQ4MzdKdGpmT3cwNzhMcVVWMTM0CmVhV2FtYkpwQ3NXS0IzMEtDanR2
            SzhFOEtPWHp6MWJLWHlndG1ybitBd1EKLS0tIDh2NkIyb3Iyc3JtYmh5YU1rMzdi
            MHJ1NUx4RWNNR081MVdNbk5ZQU45N1kK4GlOxMxhyReFFm5EKCqy6EQLnrO3mGRJ
            w37DOkS7bbgmyO/gwWouaaFFh8u67INHm2SPM1DUhaM94IU920WEAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T15:46:34Z"
    mac: ENC[AES256_GCM,data:tfG7DhOJIc0Wvy8g3Plp3kQ3ua3l2ZjrEDxSNtgTrV1Rx6CdNE9xCowyrGe0uPtM7s701IrBFTIHqYlV6edbIaGY46O9xh50VsICT8VOvo689avmEPPEq/N0rqNixmj5yfd6g3+neeJ2n++IG5+tDZAMKPIUCTFcUttztKXh8Jo=,iv:EnpwceVBsuREY7SRCV9FdouTYnoJESBTdMc6gNPlA9A=,tag:xhTOpk4SHU0EtvhuVOPxVg==,type:str]
    version: 3.13.3
