# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: gitea-backup-secret
    namespace: gitea
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Q8kvl8ZjPP6ydlYitEGzmgTVb67QFw4jCgF5ssbvyXo+1UKErTJFxKbkk2p7LwW8MpwC762B3ZhMb+Ur7nJNnonrhrJyJz2W,iv:TXMRzxF6/UTwACU/GZGeNVmLwEYM+mXvCBzKcs7O1sQ=,tag:icP9UqU0BdDw4TP9pzFPsw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vFh7HQ1as/s+gIi78nojt5bnnWCjPD/CiyS3BTBVRFHZylZfZw2TOzN8npCsMELJXDULmAtmFjDFqJERJ0N5U18s0Xqn/RV3,iv:1T6nVrc1rxEmTeO2JWdwcWNZ2EEuq8XTJQ2reGXlJ/s=,tag:ESQF6yX1r8AdS95+egJbeQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:RpUDnoLXqUQ7tp5dRQq8kCG9IfhqCoIOikOLluyqWg27Sse29+K02JZvwcQHryQ4Dm4oUtYWiroaP7k4pBIc3R7Om4wIjtAw,iv:8C1pTvXLDFEWZvyHdl6nBbGZsdlIk9Z0yrfy3Pq2eU4=,tag:CQlle0Vj2bKqUz+rTLSxRQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:CO1mASOrYJODpEZeJQzA+ob4IRFzbeKyPyw7L9Jp1t0vH7AceN/gjvqE2/u7+Xxx9oRIdqFgRMRk26Qk4FgmdCP7gNHlzHmQ,iv:P6/h3lAuv4o5AXdLEHcTr21u2428MYF7ZrX8OEfET7Q=,tag:nNk9+alrnoCUoWOzF/3Ivw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q0dpekd2MmRCQlZYY2xi
            UzZVNXA1VkVaWE1NV3NSbHlES2d1M1lqVHhVCmdUTG5zMFhiQXZDems2eUJTQlBo
            VFlhQWRmaE5tYTh3UXVNelZzQkFyNXMKLS0tIFEyTGFCQjFEc3QydndtWlRNWG0r
            RmtLZERpUWFOSXhaam1yaGI5THI1cDgKi9azUE1zHVGRFIs8H2SV7JifC5DSZKZ6
            1vrjI+8xiMwwOLeYjjMeXkQyndGrbgJ8jkNqaYGt6rHhrS3iD4oj5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T15:26:09Z"
    mac: ENC[AES256_GCM,data:a/P0+U/rH3U079EHp1ou40WjEbHHx2j54wvGJ6iIDGbm/I2pPk9qc7ZtHIZ9NtThX9k2RbCTjY4lU8tecQljTfqncweNuxL5yptWPhh4JXzcXx8r5d1KDxOiEi47gqnnql7aKfrCtkgkK9v0Lq2qcm1TOYaXTLDQW9Zdj+/ApKQ=,iv:udYb0VmdAl/43ytdn8wj5Ram1V1hd/02xMS/Vvtf26o=,tag:oR12HUy817zInao6ZmA/eg==,type:str]
    version: 3.13.3
