# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  maxHistory: 2
  interval: 30m
  chart:
    spec:
      chart: immich
      version: 0.13.1 # datasource=helm depName=immich repository=oci://ghcr.io/immich-app/immich-charts
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: v3.1.0 # {"$imagepolicy": "flux-system:immich-server:tag"}
            env:
              IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.immich.svc.cluster.local:3003
              REDIS_HOSTNAME: dragonfly.immich.svc.cluster.local
              REDIS_PORT: "6379"
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-library-pvc
    server:
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-server # {"$imagepolicy": "flux-system:immich-server:name"}
              envFrom:
                - secretRef:
                    name: immich-secret
              env:
                DB_HOSTNAME: immich-db-pooler-rw.immich.svc.cluster.local
                DB_PORT: "5432"
                DB_USERNAME: immich
                DB_DATABASE_NAME: immich
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: "2"
                  memory: 2Gi
      ingress:
        main:
          enabled: false
    machine-learning:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning # {"$imagepolicy": "flux-system:immich-machine-learning:name"}
              resources:
                requests:
                  cpu: "1"
                  memory: 2Gi
                limits:
                  cpu: "4"
                  memory: 4Gi
      persistence:
        cache:
          enabled: true
          type: persistentVolumeClaim
          existingClaim: immich-ml-cache-pvc
    valkey:
      enabled: false
