# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/persistentvolumeclaim.json
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
spec:
  storageClassName: csi-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache-pvc
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
spec:
  storageClassName: csi-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
