# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:o9BKyvjX5wlgNbYY3NJ3PFdEzOtCnKzJK+Fg1wbFCdY=,iv:wM7b3cZZ/0S3FxR9MEdJixuCtTinjELpStXWhmME/hE=,tag:EUlDwBR/ioVGsf0D/gHV2Q==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:mRQqnFEl,iv:KtmEZX2p1quWa60LS268bUbRsvnPuXewyyghaZIPaCg=,tag:mTdfnlxIk83hzyZ2TY1ZfQ==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:A74+oJ20,iv:BMTDO4XwB9izRO8orXWU2VYyRpwx2hVaneCTaSeTW98=,tag:LrgCT7iXqhUpK4UOPzF07A==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:XDVOImVja/Pf66w0hYRhURrmG4NELOMeAgS50ZbWhRw5VWhoXTYDj8ACxzE=,iv:B1gTu2nYtmyA01V9oGCVvP378DR+pClUEDx8qQqyEMM=,tag:bY92K81YiW4KT4hJ6J/CXw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:WjcYPoNceQDHDnM5DFXSEQ1l8rPltQQ2SJiMZAiJxaNlYv6Hw6qhRAxr/9M=,iv:6pVBEq4G0kzRIegG5c5KFSZef63Y6e88UpxtpLtYH8s=,tag:zVbzuFG3CpniftxBS7WtSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRnpudzZsaUM2b2tNY1Zp
            VnQ5emNENkIwQXc3OVNlbDlGVWNzVlpMeDJNCjhNMHdxYjdrY29mWW9aMmtBOVpN
            Ym9FdG5va2gwOURpRDdORjBNT0s4M2sKLS0tIFpsVTU3R0Nqbk00TEZSWGtLY09q
            dXdZVyt0dGlrdVRNQjUrVVVoUWFHN0kKiRAXjR9d0wFb8fQb2YmVmD7EeHhQv8fE
            buFjAL9ZJbdwRrFT6yGfVQMWBxpQqMU/J77Qd6+6OZUlgi/lUkqJqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T01:50:27Z"
    mac: ENC[AES256_GCM,data:HcKMDeWMh3VXTPZ7nNwyl/PzA+Bq7s4to+tJa60MFgE8yxFj6huibJqivmQn4v1lRSuwmxY8kSB5CLFLdySNN1XxsiQM/xiVJnbr/C4nEyYGKoeNRwJkJtf/lCqG9k8lVgw2FsifCGc91kmebcjXH/PmwvMFMB1hN5oYIWObwSk=,iv:ZjHJbOoQgNM29aw/CiWLt20Bb7Fw2ige9rhnE94Birc=,tag:tQDAAayqsMnOxBYz5Y54pA==,type:str]
    version: 3.13.3
