# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:d0YA3Bhhp5KgnaOkmmBFYfnzQX+TAgxrE8LKnQ/FrfBkC9JIaEwRLUPgqOK4uOVvc/JHvjL3fjUKs/bbES7JfFq4qCdbHcl76LY/In2TsiV8NH9yMQR8wwFiAOidfIvuf+KQRTDKEzKtQodo8peBp+Duh/59JdBXuVOqJR0g2EjEI9Mu87/BBuh+TuWvhq/yPijcXIPo5UjJr/a1aM3u1iyVD9HT/LYoZkPGmWiRO2lgoSonG6X7zA9aDhUXxXhWA38GF+FFKyhaqLD3C1iyHybLaAd2b3cZCcp3FhmlHkc5ajPS6p0N61fCEYyt/F8AnK3slBC5I8JoHuGdvSUd7akvKGIaKXzCsf8nZUUBf4ybwOkfgBiRbhKjOMYXG0nLhhU=,iv:g8AYL7c+iCME9xhgaCQLxRfJbCV4JpMvi4uQl55IYqs=,tag:s9T1XHj9GTY/ZEGb3wfoJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eVloZlJNYVpMTFRBU0pi
            Nzhqb0s3Snd0QWVNc21hYmlEZjFkekw0SlJrCndvc3BCMklReGJQNkJzWmYrbVp1
            N1I5ckZTMGFIZE9aeDdnZWdVNDhFNDQKLS0tIDZCRTlPSTdpYXNRSXVSNXo3cytG
            L0ZQQS9obXQva1JjdE9ncXVjNEtVZWMKlHpK73XYsKsu1HkApOiYx88N/qTgZ1Ng
            dNeC3PR38IyDOQJE7bIeuVEPApeVI7/FZvS5x+ryKqSR4BwIR5u/WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T15:06:17Z"
    mac: ENC[AES256_GCM,data:ssq8uyuisidMMw9skzidAdfIfH0+OL0yxSF0Kb2LrsoqjYWxi1Q+ZhYVSlEazIwuIoTqjDlHIUGflUTjzMgzzFsaZypu1WQo2jecVsYjEk3wxEWLjQgu+FXpayeqVtW1xaRTUqfntHgJ53TuJTPgarxFQa1LCq71nYyZPU+KhVY=,iv:6Ab2jYOa3QS9DqDx8SNry44hgXZR0v4opUIV6X2oJ+g=,tag:FGoKOxECkV54LRkdwldlUw==,type:str]
    version: 3.13.3
