# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/policy/v1/poddisruptionbudget.json
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: query
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/component: query
