# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: immich-backup-secret
    namespace: immich
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1yhpKgNah9jlPnYfnF2jTmVZr+E=,iv:avLk2i3MduYm8F/QjWMYyEK8L1wu9V76a8/x8tKPKE8=,tag:OMYNbzY8lXlYvlqjoPFUfw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/n/FKfspROC1ycb/+Z5IBIDC/ni66vtK5z8YbAio/ozVX6bBmk8otg==,iv:Iv+Mvb5dwvRbweqIKGIpZqmL8knRonVVyx/yktQXqxY=,tag:PBUojoglV7WsLiF3filZ3Q==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:CUF3BqwfAyNg600X2Frq1njyLJizuYIXCAgbcPB3YtA1i68s5B01h86j0TYfjzR9KuarquAuXQTMK56DucmZ/RGKtuG9lqSFqFxyra9T2xvwPLomYsRb6mCV2gymYBk=,iv:k823c0bCgwskHWF9gwc+pprjFmE+5PKll7BKKpvQ/sA=,tag:FXfVKWk6mvINyye0gSR1NQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:hyxO0tvVKYzKD84WAgYO9VQOTUzlEG+3XDmaBi+eultkTnvYd/erjXkmunM=,iv:G94SOyP48R+GKIl+kBq3EEh4DSHZXMaS9QbEZGnJs/I=,tag:soDzYOWEo9nRnD4o2Wefbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdHFBQTNoOWNiczdialdh
            UVN5Y2tydFFiWGpHMHd4NDhiN1JtYTN1WEdjClAxNGFkV3QvQnNYQlp6TXpzVW8r
            L2dWam9QWkhpOFVENkhUQmhtdmNoOWMKLS0tIFpOaVdBZHI3a0gwYTNzMlBOeW5l
            YWtPbXIrR05vMVdneWdYS3VtK1RLQ2cKvSGCe+WnV9z+V/qC6LzUtk/uz+7QXlEq
            SYMUHjt3VAGBq4ttXbozINO2sQQ7Y9LFMbiDkCzkLJCsTsFx2tGQSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T15:28:48Z"
    mac: ENC[AES256_GCM,data:7I3Gh5L4WwrTh0Iiz3YOBuNUCDFVx70Ovcco8pwoXqfYKMwIBmfpHafgShk1hOkxdUJS3o096C6oXWlTwvQzegefP8vbrg/HObLz8KCW3KrhijoZT+ua94JnZf70hyZB17BnH7j5uPqhOqFDizg49mYmVn/CL3oDmGi5scaB1GM=,iv:wYvTtbfVZHGPezUEAjVIDZl0gZ9j1XHr1930YsDNFuk=,tag:CrS7Nv5i4jgbb+eATmFOGQ==,type:str]
    version: 3.13.3
