# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./tandoor-postgres-superuser.sops.yaml
  - ./tandoor-db-hunter.sops.yaml
  - ./tandoor-db-user.sops.yaml
  - ./cluster.yaml
  - ./pooler.yaml
  - ./scheduled-backup.yaml
