# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: tandoor-db-backup
  namespace: default
spec:
  cluster:
    name: tandoor-db
  schedule: "30 3 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
