# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kellnr-backup-secret
    namespace: kellnr
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:n5IkCfcyc3AeMQwksLtjGRFW9wg=,iv:OvHaf8jXu5Dxo+sI1jm3KvFDFHU3Rh6BP3neGYX65mk=,tag:y2fb7S4gqwVZPHKMifqTwQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:k8KEMguRLJO9AY2aZEG6G6By9OTT2UOaGJTeo980PPc9hLnBIco3lA==,iv:UuMlZMSTccszLygBFKBlPRtVySgLHtujHXMifpocDek=,tag:VdzS0ehfhXGdVCJf3H8HNg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:gx+lNbnCo0yUXuMHKNUFIyxBfKb89OBWZJXLWCaVOMVZ9VhYaw7TBLY2s3MZchFdNlY1qNkhnnQCyhXVvIuFcqa3yO5Z7JkGQNkzDtP9OJLTvro8bQ+u,iv:hkMcfwQ8kHTg7uf9BJOoWc5PdSqPWE6zrY6fbQ3UhUI=,tag:USH1COZF7Qc/BdKcbeZs1w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ZK3maPpPRnSM1RhSIG80BwAFNYHzTJ6r/vBq31DKtzTVtzj7JAGCJ4ywiGo=,iv:7yoBEdMGR9oX7rC6kEz8EoDxt7B9M+HDr6gxX18Y5Xk=,tag:JbtuSbNqpSr/wfzb6tXWqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZXFlQ2RKSWR5WXIvQ1ZX
            ZlNmQW8yby9UbjliZkRGcFpXTE5SZjU4aGhFClV3VWtjcXRyYlp2K1BmUmhrU0xS
            d1FDT09jdVg5WmhOUERLTnN5WmdoMncKLS0tIFpjNWtaOWF0a0FXVnF1aUxUTlR3
            Tzg2blZwTXl3aHNZWDlyRnVyUFhqVmsKYf13ztTNPs98sErV0OlnX9r7m0rFTCN6
            s8DGnWjwJ1d+Vm5/vfwZIIqPYqi1EPZKX2TRBEjDnoxKhNu/J1/mag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T15:26:47Z"
    mac: ENC[AES256_GCM,data:9VPx/ndn1+v5zWzcK/Mocrfj0/bGftc/RS6QtwpPKrtSVSrZ6wzlwL8xtolgjBLdL0pMWpAeAVsQfEStfTk7wAIc8Nnxxf+prNJXADPqqME/0F7l0YyqVSsCHWlxnoQfMCnmmLhiwzU/wocr21cTuUgjttFiePqdXaBRzTtTwiE=,iv:Y8C2hJ+Vp2fqmOkqNzyW9os7Fv70Ph6ALrqdC2aLVB8=,tag:SPoYi+ac9ttXA2ExbPyJvQ==,type:str]
    version: 3.13.3
