# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: harbor-rgw-credentials
    namespace: harbor
type: Opaque
stringData:
    REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:RtZqgcVRDQLhZfFL7P16jmJWXLg=,iv:0ZHsAh6aR1pISy2Yd9MFDdCnRFYvR7UPctgFOlnbYNw=,tag:xsNI/2A8dTx/eVqbVKwpnA==,type:str]
    REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:NRtxt89KzEbL2n7H+dl3kIkkL84=,iv:7QvZ3haRXHVFjWkxVX0IeMmZO++WAXZDxhjcLWAUJxM=,tag:61owtD+vqwtnpnyHOMprUQ==,type:str]
    REGISTRY_STORAGE_S3_FORCEPATHSTYLE: ENC[AES256_GCM,data:ThHnsw==,iv:uYmXJVJ0Mr+Swuq4DKzuvkwx8+oSP34XJWit57CpwFY=,tag:EuO7pX5Au8MywnwxNMKx7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUFFJYm5xTmNMa1FuNndC
            VmozUUlwaFJYanNLUGdyMFVPQ0RRbm1TYVNzCm9kRjhkOTVSZXp4NDVjTzhna1NG
            SVFrZnEwV05LL3c5dy81ZlphUkV5WUkKLS0tIG5lS3BRb2NKT3hDai9ObFN4UGU5
            aFhFek5SNkNzSU9rTVIra29qSjN1ZDQKvAjcLNhbV66WlFikRFr9aZACHKc/+0dh
            r39vDcy3bLPkBloEUg389zki/V9YTptIRvevlM1SCAT67UtNmRSbIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T15:38:17Z"
    mac: ENC[AES256_GCM,data:Zg+q0+vMe14KKaOHUsPJ1cRV59r71gm+annZYiV64kvIff3BIVYug9cs2TBexnuOXUW+Yx8nw/ahe1VNNmKLIzTAM4ZnzMTwz1IlHDHMwrepJd1THT/r6rK+SGUZY6ZQQIaer2CL38Hgevc1GznlX7oGELO0ISORLZ8Tn12PKRg=,iv:ZSYmohPB8CkTyh91nVQk9cNU/mvUB/tBzAp9aTqTKmg=,tag:Mb3V0GmxSK92cCj/o1VMQw==,type:str]
    version: 3.13.3
