# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: harbor-rgw-credentials
    namespace: harbor
type: Opaque
stringData:
    REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:C9jSojqfpplXrSY2BZyAdDbVNZo=,iv:0We2SfwFuALRr/3KBixUMAhCKdXSGp8vZfn7o4i58jo=,tag:D+N1ucOudP1+ctPn2YDGNQ==,type:str]
    REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:657EOizV3QEsTi3Nj/emOsMMAoNs7UPFA+N6xS78mSJzM8f2uy6+Rg==,iv:+02thCj+P6Q6n2yKQbOMERsDdsoJPxEHRHO5832/fAU=,tag:Zpy02+dh94KoNptu8CBWYg==,type:str]
    REGISTRY_STORAGE_S3_FORCEPATHSTYLE: ENC[AES256_GCM,data:Z6e+jQ==,iv:1F2yT2qt094fEdNa9o/VRIyTtJTdjaoGpSLP459bntY=,tag:UlZp4filIRiBSYzmmlTfoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTG4ycVVXeEQzYlhtT3JV
            TWhiMUs4K2FhUmoxb3hFeFZGejZ3aGYwRVNvClB6RUFodGV2K1pxcVJmS3ZxbTJO
            MkMrTUI0UGEvcmROZ0FWL2lncHE2aWcKLS0tIEpxaFA0RFFia05VNFNmcllhcFIw
            Ujk4RDNiTWI1S1o1TUMyTFN2WVo2REEKZ9lxt3e0LJC+qEb+usjQLW12YjoFX/yj
            H0a02ipIyFwo7Y22fA27/g3EDglOqnBG7ADpyT5eE2E3V7UHMw8L4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T16:07:45Z"
    mac: ENC[AES256_GCM,data:E4r1jdMDndmXGRmzLevLZMZaswepYFbKa1S2h/bztGuRQ9XcXnscEXgvf+0W/OO0ltusY0FSKMSbeSLKiA4/wmfaGzJWwcM2mjYskxy/dbsX+Kcjx5GrqWCoZZMI3upe/tYfUkbIRVzV+PJbN2JE2d5Iti1m64dIk7FL8AcFssw=,iv:BgJU6/uzo2NPU8ZA+WSYj/qTefrS6I55+CjF5YQbO7U=,tag:G4vPg4Zku/vR6CaRq0pLZg==,type:str]
    version: 3.13.3
