# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:6fk5C3l1See4CXYJ5Ht9M9pDeA==,iv:ACB/DERgPQxaARu2Onyw0uPO5VRsDBDZE8lL17+UC2c=,tag:I/zfr8Daoz37Iwes7X/92Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:WXwwsKUthp8DWu9WJEcyCQylkOAI7tFxMXbEJNSrfBAF1pRy,iv:H4o/sCGmqeVmyDm09XwdSoYPey5DFGE59dyHCc2Eudw=,tag:6PHyZ99AqiHEDDMo/zSlrA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:oJbzlES9EX4DwNJNXdoAehsIu2c=,iv:ujVMhIkOBNNzsBCm+gXYZK2cjOUjhJ1zptkvkphxAQs=,tag:okvLe4AKSi26QOvS8jxTTw==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Hbmj0NcDJwKOjWf1TmROUAsaHZs=,iv:gEw2mosY3kz6pJAq100RrNlyPvSD/uIqQE9yjgPX5PE=,tag:CTyBy6uiY3lwWai4UE2wXQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:OM1m/uuzoVl/7YIXEeyfMS3Biv3zI9CV4nteG7lbOg50CxxXhJpJlA==,iv:g02V05KrTrI0uGRcOOz4535e5zxzLdwUbkT+JjrwZvU=,tag:bqT6arGPyaRNyT/msj6d1g==,type:str]
    PRIVATE_DOMAIN: ENC[AES256_GCM,data:JdnCvjPfDDqVoe+yqA==,iv:jVF0tb6pdAAtlX5gYWkP5vvGyujIuYxz1Aj428+78cI=,tag:YNR7U52cxEq4eQDF2LyTlA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRekxMVHl4NnRLWlhFeG9w
            RHUvQ3JBRC9qOUdUUkZjd1ZqdTB4ZnFIVmpRCmsyTnNEZTlxRGlSL3JZTWlTQVdu
            WHg3TFhJdnZ4QW1mZWhFajNQK1h2WTAKLS0tIFZiUDcwempINFBPWjJCak9zcUhw
            Z010UEV1aHJ1VndoZS81R3R4ZDFBSVEKaBFtXXHbHQqxTAVzbXmMJVWVbnNlZAnK
            HN7FoI0nhVaM8YUiou8VujFXvAyhR47heioM/OjlwqZQ0hlw04ktmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T17:04:13Z"
    mac: ENC[AES256_GCM,data:ms9lYM0BApVhWFqnBmCuKWuStzB1IKp6Uq1S+5ZZjrQ8dzS51HwLEwnt1LH1exvzYqZRDoo7kIQLQpraIPZCZgv9rD6w0kMZe56XffoL3hDg7tUyTywclk6D6+FobnJiRrfvO3XOFhe1TUb8B74+4yznQVILcOg3oxymWRu6C00=,iv:pU+JNtoW6sMcXIbegSip0ptwlq8zQy2prfusgHL2FPM=,tag:bl7mlGrUoM0P7DjPkS5pzg==,type:str]
    version: 3.13.3
