apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:0/yyKDEQIvX7Pb248yB6apiCiw==,iv:hjKirb6VmkW00u2y3b6/KMhmq+ovaN437vEKUFxd45k=,tag:lO/AISuQj9VKogDB3iZS0A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:YffsD3CUenNvMm1kZxGjZuBVxvFxIQZU4YsdXoQy9reZ9U3t,iv:BY8L8Urbl/7e5LBdYxmP+7lvmSjiP0Ggi6AMUyZJFNo=,tag:jNkibJtujAyx7NLD/n1ZwA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:zs0X2oXHgHCNkpncqveH8zsa9pA=,iv:iZlYS6JKJYgg3Ug6goQOnTUwdoKjzNKqQCUU8g99SjU=,tag:JY/TSu56akcGnqsJ0VtthQ==,type:str]
    PRIVATE_DOMAIN: ENC[AES256_GCM,data:mxW6YzxHps9Y7EvQiA==,iv:Y+ENuoYKtnRKBSAuI9FOHfFdRCNraw+oYp3SI5LgwU4=,tag:RH2MBWjfME797T22HXhhNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cG53V09oM1hFYytwK3l3
            aEFFMDVKNERxa3BKeW5JSkMrckVsTmxXaVdrCk1hVVBrZTZmTzNtNU5Td3RubC9O
            dGlIZzc4L0NTcXBCUzBKQzVRWVhCOGMKLS0tICtOdUFCNi96V2dWYWVadDJUV2NZ
            eVJ5N0tXRHNpcXJYZlRNb1lzTks0NmMKyRQUZbVK/NjJCxEJzlIws653R/w9vbGQ
            zv+gbDpSsujlMpSyfWhSzb8qLO+bYoetu1J8S4dIwSGoi95V5PGiAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T19:00:54Z"
    mac: ENC[AES256_GCM,data:IKiOnssAzrHIrOUwIz+txx31JP304beztReLy38OZkmZk3HGNEzXfi3Mul01ea1DJ0Kk4mj7bWdp+sV5Kx+9QmFIjIYDtnp1mu0QfjUxFIL1O8hyQShr34kQZW94B+E78Sg/E/LegspnOthbbr84SktHGygycGIF9cXYCV4OU6I=,iv:QfDJcKKiapKgFheGOuYNGIEIT8cgdvcCU2gtK7USNHw=,tag:OdXx+pAV1qhWdqpjN0B0bw==,type:str]
    version: 3.13.3
