# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/persistentvolumeclaim.json
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lancache-cache
  namespace: lancache
  labels:
    app.kubernetes.io/name: lancache
    app.kubernetes.io/instance: lancache
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
