# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: openwebui-db
  labels:
    app.kubernetes.io/name: openwebui-db
spec:
  inheritedMetadata:
    labels:
      istio.io/dataplane-mode: "none"
  imageName: ghcr.io/cloudnative-pg/postgresql:17.1-1
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
    storageClass: openebs-hostpath
  enableSuperuserAccess: true
  superuserSecret:
    name: openwebui-db-superuser
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: false
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store
        serverName: &currentCluster openwebui-v8
  bootstrap:
    recovery:
      source: &previousCluster openwebui-v7
      database: app
      owner: app
      secret:
        name: openwebui-app-user
  externalClusters:
    - name: *previousCluster
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: minio-store
          serverName: *previousCluster
