# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:VFVCy340YLg=,iv:LLwrueXf0jaTD4HBJufpac3VooFmT0GcOtYHXsZxTiw=,tag:vzPSioBZ5ahyuMMfqwCCxQ==,type:str]
    password: ENC[AES256_GCM,data:qpjQ1ilW+G6Fh1+ILvzj6yXheKzpsvGmhA==,iv:2inzVUswVoVZn2XhLk0NVAUMQT++Zk4QcM8dzoZmpkQ=,tag:GzBAnI94M/EOPIEoTZV7bQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQmRMWEhuSk5pc2MxWjlV
            Tm5qa3ZkdUdSeCtPWlRJNWNuWC9PdFQwRUc4Cmg3YXlUazl1b3FsbjltYjBDKzVz
            YUVSc0FOakJiMnJ5d0R3ajhFZWYrUWMKLS0tIGhBcWdIQTArRVgzM21VaFEzekpi
            b3ExbzB1dmFROGhUeFdKM3BVdmt6TjQKhzs9k2/AM2ainYBEmqpAnNeAxmwb2iD6
            V8VPQpM/9b7s8yCnzxRhhITLyqmUmIhbK4CrfhUEORjeOM7W6mtqoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T21:20:41Z"
    mac: ENC[AES256_GCM,data:iqdCFtChXjso/YPBrcN8c5H3ROniyx7W2MCNIjLfkaPAZoViKiK+i5AFROPo+Tu4X/to1YJejXAYJXXAyXyJK9Z2WqPRHQQRRzbWDObQzk0fz2OfaqCO9NJ0vu6shjXdv16BTlKdckZtEpwhTcwE3SGrM5Avdpuf7Ovx1fNNydU=,iv:TwvHg0Wp2wXazIz1zKNOPIPKvd7FlZoNkmNcoH8odLs=,tag:IGR0LKAU9zRXcCHm0NhIqw==,type:str]
    version: 3.13.3
