# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# S3/restic credentials for the node-red VolSync backup.
# AWS keys shared with the MinIO volsync-backups bucket (see vms/arch-linux/app/volsync-secret).
# RESTIC_PASSWORD is unique per repository.
apiVersion: v1
kind: Secret
metadata:
    name: node-red-backup-secret
    namespace: home-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zjVCkg19M+ofDs8bNX+VV2dwI44=,iv:6NBMkAUOEwJ+gA+R3UH3P21n5tljvu9jSHTZ9OFdJ24=,tag:ZfWMRZADHC/vC8Vj67Ff9g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5GAc2Y37i2xYboOBuLtH7X4gsGn5cmWPb5z3B/wD1/RcLT9iPRVU1Q==,iv:VA/LPeHOB0HfkFaHYcH/b0LwA2zkY4NKZYBKthmWCS4=,tag:UDBn6BWXa2RG8+7+RVQ2QQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Nnz0SmkNew4q1h2Tf6c7VsPHiVNFbU2mRM1iVObybpDZ/MX5RmL+tezQyLuPX+BhI7NZCs3MwF/pitXWPC4Lue9sc7mE0VVcMCh81m5ygWQVuiaM7Kw0sYNNfCyYZA==,iv:x/CJ38b9woaTmiK3WHNMnRwHhCLyGpFD7xcgxXBO+Xw=,tag:d/KNpe6fVyM1DwFauZWOyA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:1Z/DzijjWUh2z3I6wB7QbRXOCeFd4Wkvf3q8Zbxk4Oc1zQP8RHd/ht/OWT4=,iv:nHVgNaS8EG5oVLc72MMxsF9J+01QCcZiyYO11rcWFj8=,tag:w+u0oPihLu0bmXZSk3nMTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXamwrZGlKT0tsRUVXcGVP
            RmNXNWYvMXkzZ2d5TlJzVDd6VWdKWFlYa0FnClFRTkIweVFuc2hmNTFzRlV2NDF0
            RFhKcENoYlB3K09RcE9yQVBjTGY2REUKLS0tIFU1aGVKSDRVdE1PUnI1WjQ0aWlM
            cUJYMnV1ZVZkeGRDWmhwQkNPRHJUc1kKeDLAikEXJW0CfKOuB7w0/FVxV/0o27Y+
            ZYl+4cWRqYYrHn/wQY1AQDavoiZNXMeLWfb1GEAHVB6soQCQtPya+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T16:00:00Z"
    mac: ENC[AES256_GCM,data:4jeoUVPd8su4FOm+l84vAG1XmmcDJzFP22zebl+1BFfqKzOnBfkO6y5oG3h+8cgArdKSn7ncpyG2u8gYZB62p5DAvCVx0A9CsdNd0YMizjmVQvbfKdg7SD4o1mim3sJ6LxSpqlTQn42UhkAz6lXJ8t3eeidqtPx6hQtCPrkxkLw=,iv:CS8SmBFcu+x6zzrBardBMxkrDkfzC6IuJeHIl72sa2Q=,tag:fdrPo5keIcxN3L0doduoeg==,type:str]
    version: 3.13.3
