# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-kube-prometheus-stack-config
    namespace: monitoring
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:bgp9AS+dN9eV4DhANKgQRB2UJUJehbV0oB4WYgzvX+5o7ktQ4VedzmKEwn2eAVcv96lxppBsLi99z12gFYjS4YNvN15L8EFF9ZXoNp+6s4V3p3M5KpTZuTCzuhwvSRYiWZ1oIgFMdtF+r9hppJetx8chNyxT7d3By6pYhEAkybOOxQsuV/P7APCju/KK2S3iCDiOwRjdYFV0vBuY9sEoiqqfe31AtOuFfzHpHHbS5sSuOQ3Jhaz+GXMODPuZfboMVdwYggMs0D4t5cMmEmKKsm2tcOtwuul8rPCHwjqN66ZjZcEzd9GzQHJegzVmpTYdRuFdp75v+W7yGAJQ6nHfimPJZEj+v3WmoF5h2Kv4c5rOp6lSH0ELHqnyuCCIngD2W2G3Xujf6xi6KQ4aWXd5iXdJrCfaPejjf5DYSX1GmVDFZg0doU5MUn9ZxL9KOPnAnJWA0AQa64h/vYDKWgzGkzoh6TuOswTYvaWhw62YllqoR5DcxfOgfKS5pnSXAjqbdeKwLCehSDGnL/8+kZKW/n6uMxmqos2yZlzyssGVc6/E7W7a3LTN7Q0rZnrQp7I5e2ttagkzJfx5VH1FyfJaQZFyBa5wp3bwo2m/iQCCD+T6JKjudUyTEwtefYjMqmOi99+iqE/wJPqga7kCkneKJRSscZRILUaYA5NxhQyFINlz9fWhH7h5c3z6OZaXvsYfltG2h9m2G/7bCWqrDIkrA1yZTgYpNr11CWKIUgQEEnFea6VxoIeMhsCguhYS2qEN2OH7a2NGXapQzwho6TnP6mVX5fEOrGbWS+3iebuBaxLW2NccRtIxjjhiGSVW+ElL9Fak8VHs1CUCDMtiMgtaw0647R34r4PyyblxCTTh04FPYEhS6z+32JmPanIXZm41jVfyro6isr2n/6anfLuSmjPsGQJHZy1DTudYWkNCEwTifK65IxqLJgzFaCx+SPlaKZjLnmOY4xq49a0BT3BAoofAAN4oNreUaT86q5EQ5GUPz5LrDACP3RkXApBVibPw8Z6P4GgJyyLCXO+dOLGVbG2as/2C30aIjyYEHl0prt5RDfINDWk5aC/2yIJUZt6uzI3qD1jZclB1wPavRoTXjvwug7PLLW2VP17thIN/8/xOw9y+4NuefUI2nAbqru3xQzoWpYm7p7mahbjnx1Y+DBKh7wj+UirbWKKsJDSG1IP+nouM2gRoGVgoer1UnzaTXj+de086F8mOt7xSt9ZCZ+AejHwxWOWn5AageqHr5FvI+zkac8T0Piqz3sVW6ne4WBpsp0zCjWwylkS9aFKuwGHfRPZ8x7Hf+X1e52AOEdEo1ASR0AA39onaZC9LCEDyNLhbKzP5f6FK8ulZ6rcvpJio04su6C6kkSyLvw==,iv:ypRVKfnMAqUYppzJYj+pwqHJHRLzbiEJxqeEo2vCki8=,tag:YvTWPpdHZkxBIuQv9Yg2lQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaXB2NFRHcFFkN3VTaE5W
            SDJhcjMxNzZhUG1ibzY2WnFqbjA2bTJGMDBjCmxydis3eitmMzFseEZDblJyWjc3
            WW1MS3pFbFRmZXF2VnpWTStZSk1oQUUKLS0tIHUxSmFuazVoY0c1NHhOMVBGYlJF
            aUhHK1VSNUZ4RzFxTE51ejZOd2RGQTAKjaJax9cG0ecefpIA/TFkgoeU6zV+HZub
            HsLfxDDulaFvKdPXq+mJE0cZvN6p4RrD7iEPlJLVTl9kaOjNHT6zUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T02:44:37Z"
    mac: ENC[AES256_GCM,data:3ft3Qk8tZ3QTtkIUItsOC8g07GWZsomb7F4HC9Gqene8zqova4X6vEBvprjEvBaTEOqm47TlIjlrKxENWuy8OT640eHasTRu4OoeHzD7v4v5SkR+KBwkEtgJE1uDC4fn2mKSQwVYHhtmgDwoYdY1OJFfre6d+New88xFuigoIBo=,iv:M4KzU2D3ZWFCcesAzbPMvGmyMPiziFHUkCwHUm5ntwU=,tag:kPx9nvZrTVMKxWzeXJEvLQ==,type:str]
    version: 3.13.3
