# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-kube-prometheus-stack-config
    namespace: monitoring
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:JiFI8lfFIlKyUGuyv27LYNQGt0pK5Mc5jzyyVk6OwrQSMQZpQnM+aHw30fQs/OxZR6yw1YviuRD1qjfMD0CTTPCv5NFlNzrMhn6LwdrA/8Qy6afhWjBRKQAd1qAhO/pWQEdRwoH634BZqbdd6n1dX1BOUU7NWbH5uG6ERWESTxOwu+fwKfS4JppCLlmG7nuMLCuT0v4GPCirPaLbYCv3pFzcZlpkycGEcLq8XWb1KkqB4F6uXGlGxgKPE4m4DxcfxELWv9m/q4ju9LU/yKLraPdxcUpO1NJLtymcCeM47Zp0WKnsyr6GajYp6FNMQ74hILbGdEgz7j9/O5+qhYmAXH9Ab88kmFelm5MPD3sJiKBRh+oF5EVsOdR8vVwvOo8RgwkixcYV4n9mYG2MO/WePhvUD4xU0wyukimgBg+yPqSzeVtiQwNqSNEWKe+oScGgMp9neX3Kosri+6j/zPs+ZBtRzwrznonpNs8lTJ1MzEl/DhztI5v7GmuH796VBRFdikT53bEtDzzIaFlM9FAEcr8pLPEJEKwIpHtKFcTq9pzlv6XU8cVoEGF3p7lURUtV2bUHE76ExDRK46ZsrV/c4mqhRhksIeh+hZXJr8SQ922G/7f15U+9ubyvaYO7JpibWUy86iA0fxvHwIIWBgp3Apu5YD/bWnkoa3+dSOBTozPf2Q9tqqhITZVRtUti6KOine/D6JnUJVehZdgoM7FgmIVkPLioKxac+Itk8rjqJ2EuFoLEO7vCbF3Zwo5m7r8POIFsDCjTpt/G4+OzOniYnXzzt/3aE0uyunmB69STqvi27u3k/dQybyJZDJ/CSVwC/E/z15KJ3YUAiW567M8ZxeBtRhChuBYxOxbN4+JcJHV7d9GT0RJLInVJw16MXgn3kzX7/bOwOLaSm2Zd7Bus1+GOiSEmAXgPA5+myOcGHR4P1m6TQcZveowDIRw+4VJ3nqpNVnWxpO47VysSY4VMcmXqYIeWoKWJ03myy75UkWsmAwBYWVbEdRI8rH1tqqPpoas2WvY2tz7FnbifZdTcisA5f1vGRH2j4ti4FlGaLaiEs4Os5WE6SAtkf/ZqtGxepjfV0Ok5xKDjlNgjOxc9lyV84KrCmOnpRl/sANm3+2wTdlgQuCt1ldUnuPIM27tWitNdzEvecmDDlpU+y4bihxrmr3k/P/b2oL+tjQWCzFi776B4HoU+P3/nU5hfK4sK6l/schc1WfiH/iRcVSmW7m7ZXO3vUt7jTgA=,iv:W0G0AJMAjhojutrsRRfC0RT5iiS5kM7pLQEgRD3ZEqc=,tag:Hsy6aYPwntEpXg6tEapnug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArazV0dGR3MjA3TXRERFNW
            UGZsWks2OU9keUNWV0hwajFqZ08zSzRlWkZnCmE0SjYwcEZOOVlVZ2tFSjdLUG5z
            K21nVzNOWWxDVDV2TjZKeWRWaTcxR0kKLS0tIFM4N043VTZIQ1dFQ2xsZlV1WVE0
            SkN0cGVFQWpWaVNBdEZiaEM4WkFiaGsK0I7bBLKSzwfCzFPLg4XPrfIY9tONefrV
            szZKCJYCISCKremjVtPrDvTCbGRm9Cg+0mEklImPvYpYLIzZgNYfNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T05:05:02Z"
    mac: ENC[AES256_GCM,data:jEoarA55SF3IQ7Xu5wsKe+YggQX2Y5p+OvaL5OPuwSOhTvIf+LXBcAZYY2teXvCTaPKXoAzCX1U2qMTzQBi1Fz2khuFPbMfv/B6DdFd589neypjkaiGgHjrBCB+Nx8EPAmJfBeqVLKiEhDssFaIruhDXBUQPowPMrOaUup18G8E=,iv:T4y1krd2pFVu9tUEBh7Otu2MZlDxZVf04f5RjrWpxk0=,tag:0H7GGpLbgZ+tcoG1Y8VaVA==,type:str]
    version: 3.13.1
