# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: monitoring
data:
    webhook-url: ENC[AES256_GCM,data:XZkbL9qLVDVl0R82LPzcHLhOxiVub4TzRwzgq3cPzZX42Kn0p2G6TpQKVLg+yqpTxPkeH0lnChBsh3YAqoB5gKrGjM8RAl2Je5kevHizPUI/kHceqPVR45uRL6pya6YI7ptHm2ScSU33XFxo23ML2M1Do3ZLpKzDRbZ1DjZf3sgSA/eYiFKnIy7dDWGSRM8Ae7vhI2nGxrkgOYsptQD+qIb5Wi4=,iv:s8dePnISkNALFRWOaYCZpULEWONls3UmopUcGlLhdlI=,tag:+6wUBUBq1uz7JLYyzcH7MQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdTlsSG9idTRqQlZ6UmRh
            Mkh3VlJVbll5c003VWpHZFNQaHVKQjJJZ2t3CnN5UFJ2bDVZVGJqSG9jSUErdUt5
            dlROc1Vic3NuQU9IWlVETnBaNWl6QWMKLS0tIGkybmEydUo2R1I1Tjl1c1hRUllF
            ZnJVN2hCRkxrYk5lRTRFZVQzQWt4cHcK5aDHEjQJmMQ7nA/hxLj9HifN1ZaE18VY
            2PJ+jctE2B8z6KnHeRLZRlRUm2/FiGpKSzJKcs/jEySMFPMk5sRGbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T02:50:50Z"
    mac: ENC[AES256_GCM,data:AU7WtdTYSjwfRqJGfJPmhyb5EkyuwwiMdwFNTJQEU+H2LiCWF5B5NsJVSA3LfPs+71n2DQEx8Qb/f5ua64Rq+sDaqEN8FBRzp/Qh1pGiu8BbiVlJTD7ISMwDzaSaw0aLXFDKfaoz8WMP2z/OvqKEsunjjht0hvaADM9bFRqCPD0=,iv:BgK3+jJqEBv+TR0XHMFnprRrtgVu057lfPTCqYQoEBg=,tag:hDO4VLsQwl7Gfpx4tLUNQQ==,type:str]
    version: 3.13.3
