# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: arch-linux-backup-secret
    namespace: vms
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fen33ggntc+sJOXX/z1gKdGtrJ8=,iv:+2iem1i4crxuLTJIvQB0I401rk3XeH5A6A//+alrTyE=,tag:4Vi6y8WOdr4H0Jmwj8GZCA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:M9TW3YRpkMwwt8EEDIm0O2FjmJ/jFhmBqU0OTzV+C9bhETqUEeLIhA==,iv:sg2jx8WaPzYGXU+ys7G2sb72c1MB8eRlIfOV1C+peVU=,tag:nP26ahHF7xKWOxjLnaCm1A==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:sY5ZLUdlPO66nr6EifyC2fg/j2Yvk3u+DhKjefqL1YAHyTFs6WKdQNuuX8lScu9xkq2Pr6ZZYOnJNYL3dsFOc7nIreNCytoqCMmEGMvWHiSUHoRAb96AI/oW49zC,iv:AMqzWKqfSbkQn7MvTop5TjR/u8N2R1qhTlsORiFwmQY=,tag:dgHlJbnnPpFeBMe7vpVVqw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:JV+h+4WqPyikaEx17OcXom4i8aqvmmASUCjCQPzWIG1GTZ+6L4vEq9c76UM=,iv:iydcBQmpSf/I2/DxG2q4wb7Ey/2Qm05V56YOgjfxfRE=,tag:c5+SwO3wZjUHWj85sv2cMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKay9zMEQyVTI0Yi9xK2ls
            S05ZOFlqV1hXWU16V05jR1RBcS9EamFGaFg0CkFkY2ZRdXNUaitkb25OdHVzTVM5
            bXVyV3pxTVdkNFU5dk1LSHBWWGZFZjAKLS0tIDBUeTZ4cDVEY0hDcVloU3dWS0ox
            STZ1OUl1eGNGYWNaSnRUOHZnSkdFWU0KnsrIIEvf2u4ri0V4ON/8OrSImZzX/IJ3
            0D6tGYbbxiOwrzA3aJEkiOCfkHeRJqeLp+Ln0XT0/jtsj9Ft/n8Lrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T14:28:09Z"
    mac: ENC[AES256_GCM,data:Oy9IScYIh4c8wPO0HwRA+r9hAE5Fn3Elr6LJjNm6rj8PuOK+GWh2ntpEarOamsCHU0jPgo0l1H+KV4fB7C6mY2NM9mFPwyJujitYpXyLSLa/dzG7jUBCu5c3jTxPnOelREjZM8Kp9iw+VZeumRqWpWlFnxH0aEfgzL0nLpUCTjY=,iv:Ik/9+aWXjhG2z+T39+e1+NZNH1hAbAZKN9o93rrE2Zs=,tag:ou9eFsa+xvVDokyC7Z6fGQ==,type:str]
    version: 3.13.3
