# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: tandoor-secret
    namespace: default
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:ZxgzexZkrKX8h9+BDQIpZ6SWAMQLvvNg0pQ+pT2xIJMJwOZ5xbzw7UgvSNCzn4gE/sLJDDYrpo8qMtGJwa1PwA==,iv:HOO050ZPzt/fw8rcdNVvXdgNkpdbW9LRb2mTo+mMBBk=,tag:i/fa2VZ6YDABJpE4yFABeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJS0MyNURhVklaWTZ4Q2J5
            d2NQYXlMajllS3Q0QUNRaFcwOUkycVJSTXlNCmxzZndZMjZBMnFFaUc2WnN5ZHJj
            bjZwdVhCdUwzQU5oQ0tTN0FFQkdkcWsKLS0tIFBURFB3eEtQMWdva0MvYk5TeGhV
            VlczajNVS084ZG1UdGFka215Yk10ZmsKM5nT0ThFSh2lNxMNtAeF/QDommhnjgkj
            ppGqqCv6FDk3clEgmpGs3ZmCY/fPRx36LiYOvNiuP17ET9H5ActKSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T04:31:12Z"
    mac: ENC[AES256_GCM,data:0ZTGmgb6vNERZmgv/RHjc1O2oHocgds269+gCMK44dq/xpQczPRZa/UYP+mNujYZ5Gia5ivg+NUUdLLZiIsubuDb910BeXjZxsjqLlC2AW83PCjIrawED2qABLpBrvI9ubSs+3cevi2URPNUa2UNmHDY5ftVLByGbWBl3TgB6sY=,iv:1IzXv/qXl1vYsSeukGR7Qyscj6GO4QDU4uB+iFDmbrk=,tag:81tFZBwfG43Fic9F29fGWA==,type:str]
    version: 3.13.3
