apiVersion: v1
kind: Secret
metadata:
    name: rclone-config
    namespace: postgres
stringData:
    rclone.conf: ENC[AES256_GCM,data:kXdsB9TO9qrmvgXVE9E9sAQhP2oeMLj/WVr2r/pbXQSsJe3fpPFROI/NUKfh4j2ihUv+8qjh16RSL79gvIagkyBe4VvyUvW0dmwfJ2LMcGb7uIXvADGBl7xzEG2pF0geVmCf2KK3BXJ8+dpXrgAogMj3vPv3PjWaspMDmjX6nl7qDNO2G1HEdG8VwrhBCzCRsXbyp4Qa+Saw2togGCAgPkELEvYdNeR0uhUOOOiZJYO3JfSICJ5k5C7eBYd+Jq6JARSuK5zQ1zkJ8MBxhRSQ+U2FxJS69ASTY1n7By51Wc7yKtgwE0n9C1PQlBLIXr3HU6PFBkSsHxRMmoeHja/GL2V1uS/QKJbz8Au3FcOGBNSiYZe/8MZkFL+LOoQilpp/aecy651d3yLv421qlVenlP0K6JIrbIz4yDh1ovNnDIKZ+SoSV8y/F4tJXf6AHeRO8VZ5NRKjGd8+GYQtSaQaHsPriHeNm7LS5xOXIkcyRvGVc+jv3W4uHivByyeAJcYGq08Cn61gV+SijJPG3yuzNrCRK2TnuYVDgmJMtDwhmnN55NH+LEB77QRFhkvnb2Km/n1/90naptqLLBJZWDyzejhUUHs5hrIlcilxXvopq2BtuEqGi9zJO0P4nP4Osi/jUr3RZidupgyk7A==,iv:L+z7IkBF5Uqg26dXKjKMF4/y1tvhoUOVRDg/HJGfRUw=,tag:IUaOdvjGGUPDfrmnzZ/cvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ajFTYURIMVZXSVBCZUFX
            QjVaeWxwMDRmUU9JNlE5MlVXKzFCVGh3MkVZClBpSC9qajJQcjV5Z09lMzFtWTJE
            eFJIRWJhSWF1cjdVWXNrcWRsaVRwaG8KLS0tIG5MdFBGVisrUktlWFhjTlNFN1oz
            MDJvZEduMWdHUFljMCs3THBJL0lQb1UKJZmqQrUkmGf8QCSCgx20BvA3+2wX0Cn4
            Akii1gLIsgfiprRcwzog8oIFOPg8vUC66JgKpErvZvLur9OEiC+vWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T18:56:25Z"
    mac: ENC[AES256_GCM,data:eSyLQ4oRwTMoUJruCCAJPmeje4MNF9rIdm90fiyaHLRzse9PyBIHCMY4xJV69kkquO7x0L0dYSXKPkU0RXCBWmtiHIx7UZz2DOKermaJ15OP5z6zcriowJsrUgnPvGu/ZlF24OXf8dOf3d3wqt7ljh/zSSW7YShAuGLq2fKnobA=,iv:flH0/daQkj4mJiCfZKE1pzONzFjp3bos6z7detba39M=,tag:/fKT6vl2en1DzzxYVzjJOw==,type:str]
    version: 3.13.3
