apiVersion: v1
kind: Secret
metadata:
    name: rclone-config
    namespace: postgres
stringData:
    rclone.conf: ENC[AES256_GCM,data:yjZIGTiFCZV54SdNmhSsilavrX+KqcXvyqrqydg9IH0LAeTUzrpTSrtI0zQcGor9KJAd8zCStYCjVE3pdD7K7PSvcYTidUzKC+ZUynr2Js916Txp6zEZjOBIP+PjyGMpdTlyYGB3k6CJxuTwCt62l9uXhf5c66I+b2VQKXJKbq1RRsvvnlm33CHbE2OJdhhD7J1XfUc5nA+0KuIoVZibH6D0KLmCP5HcIlnMUHnjX7XELNRsC6/8BTZsfIljFrRdocB5RH4gVZQCZMFBZ/bMXTFsMSMXC41VvocsVoPZxpV6b9Xff4132goTdkYF1TXssn5wMWaMGm/2nEyexQ9IRfzVxn/mz0e6dL70PxQ6EQmiOd13n31lKxjWQCYnEOw6srs08ZteHzCBhK0EkEHBh5ya1uryEesP9fwji8O3ZNtLZFrk/IXDrbjUmscT1Pj00FvfSxSxmeJU9lYJpZKWaoInVocpU+bGM3jHV6fhLSmKr4IOn62NPX5hEouVGe300ANzAVa1NxxwLcGx4hT2LYoUnfWvXo7Wd6Zh+9ujDUjhYmSjYPaUUg6zxLeYmbGqMTDQotLH2jkcqWEqa7pY9rhRKfzxyScbkLFzYSubcTgpJ7HiljB4VImMVNY5hRQCe4cada7Y,iv:aKGHjwtIIgH+qod0pMGAtIYeAfRAihu8a/M4cFfLo7A=,tag:z5eGNGsztEAUB2ibzt6BXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRkhqOUZpMGNmSG1CbXd4
            TDFCSmRmdEp0bDNvZUJaMFU3cmNsTGVaQWpjCk1kL2Fhb3puSzlVYVRMeWdyRzdV
            eHpnR2pyWFhTVHE4UkdCeXRlN2FxdEkKLS0tIFdad1kxNmRUYnMwWGludUFoc2lq
            clZ0eC9vRGlWTFR0WnM0S2RsUFFoZkkKtr/hb1/jMzI2/veemzuBU+AcIX7pmqDm
            pbMIDYZDqc7GLJ1Esg+CfhO3gNtQZuv9rDi7D96tA+n8CJipDEPnqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T19:51:34Z"
    mac: ENC[AES256_GCM,data:SIp68Cc/GRSkY3cLGXSvsuDpy1t2j/jVOCqNKp+cYR8VEPi/Ds3bSXeB85cHzJIRA6Dj0ByZ/NdV5sUlL7ErZMMMbrXMFDZtVbC1bCTPwCmPLnoW+fzqXypyU5QZvk2qaGr4aEqNBSdFffr6EeJjWPuUm4eYuH89Yr1jp60MMDQ=,iv:8oS1IvLffJ/PNZvrq9XkbB8zR2FPka47J2YYlCpMmAk=,tag:biTe2viKljyEzLNMuKnBVg==,type:str]
    version: 3.13.3
