# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:6vnvBoBhZQ4=,iv:WZ2bCezwNG+7yG/4Vaym1DGjpgVplMlFSp69jDL3H1k=,tag:qn6X2UJsi6yKq0zNOP+htA==,type:str]
    password: ENC[AES256_GCM,data:uLHHtvEgqn8pyAfkdv6dGeeATHriJLfvMg==,iv:2GsfI8TQBUq3GqTK9fsuvefg12vSKircF7kUnfde8Qk=,tag:QYlQJ/9TJKaopfwujxSjwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN3l2azl0dVYzSDhOWDYr
            WUtGaTZjZXhURzNRTzkyOTY3OGlOOVJGNndBCldXT2hoL3FxbHc4NkcxbGtESE9Q
            aUh4ZUd2WWpXT2F6czI4NHU4NmJxbDgKLS0tICt3UUxUWkJLOUFsQUNVdUR2Vytm
            UzluMHVtUmF5SkZjT2lnaU42aVByMncKtRa3c3VsQ+NXFP4C5i+PWRNe+h2KxOkM
            x9EVgWxdVxISnJm+vE9H0u6mIqTGK/z7ADn9ytiHkz1Ttkc7get7UQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T21:20:41Z"
    mac: ENC[AES256_GCM,data:C1Hjd7gv1ZKp+Xhs+U8w/Qjg8rTv4CgOM+dHSrrs0qiWYUaN7mI8Tf9zasAjqC9UYMnTwpJ96SeRqZjDQR3bGM1zvRbYcOGVkGUt6VN/gPEVM+Bt9s7r6hEC2TYasjImCgCPsQlnLdRBii2dhsQG6twB75gxTMfNaZB2MBbQcao=,iv:pCUXSw1hrjzUMgDMYMv3r1iKpTLHRgqQ1YPAmpfOatc=,tag:YechdR+2GWMkyM+lpa6fbw==,type:str]
    version: 3.13.3
