# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: atuin-secret
    namespace: atuin
type: Opaque
stringData:
    ATUIN_DB_URI: ENC[AES256_GCM,data:V6p/XNgaCaWicV3tqNxWulllADKxyOmxRo9KH8swr6VqHMITdAOb1wZRTiPMq1yW9WjSHX/7ftBNsGamAD2FVLEutUwrK+YKUy/Z3eQNvHeQ,iv:nOICCVvLX1GwziZwUaKi6DaxptG4HTQyQkgWabK/IDc=,tag:VDnyMLBMNscE6/TdgprTnA==,type:str]
    ATUIN_OPEN_REGISTRATION: ENC[AES256_GCM,data:An7RGg==,iv:t+mIlB32/P214sANk0X5+ticPhJI9aiUwBA1vXsgDEQ=,tag:BmqK4QYeUxcIMyZTAsiMwQ==,type:str]
    ATUIN_DB_USERNAME: ENC[AES256_GCM,data:pTv18EM=,iv:Ic0QFZacz1b6s59J6rm4+sQ9yEmCcYMJkdivurvtqD4=,tag:EP9yjRh0r4XMpP6S7x2Xzg==,type:str]
    ATUIN_DB_PASSWORD: ENC[AES256_GCM,data:Qaguv5uNxpo3O94fCi0W,iv:PzeWuwWE7o49V54GxLToqeXldekl97+vaGyK5qwD1oE=,tag:XjabsIRbPSnDbSA666bD4w==,type:str]
    ATUIN_DB_HOST: ENC[AES256_GCM,data:hwzvj9QNHzSE3SLKXQluXy9PUwfxwwPMEGY5bJsuNyE3P7rEUavo9sB3,iv:Sv00sJQqIu6nlj0KN6HikHjEl7kFYlkPdp+2wuyOI5Q=,tag:OCidCDHb+g2E9U7AfZ8rIQ==,type:str]
    ATUIN_HOST: ENC[AES256_GCM,data:bgGRuxL6hQ==,iv:BZeyg/FucajbnsCEcwrWF2ZXPsN9W+l6YZyWoPoVaLA=,tag:R1EuKBeHjWzOXbSI8G83DQ==,type:str]
    ATUIN_PORT: ENC[AES256_GCM,data:mpY8SA==,iv:Ye+Q1oZhL9PaDbkcFU+jRouVw/14d03LJN6nlbhgeT8=,tag:M7hncfqoxArGCc+dyhDJ1g==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ywKl6T0=,iv:vEbysGWeBIEOZgE5IUgLJqYC5Z6n82m6asU1tAwODek=,tag:zCC94gzoSprDxLchHpLBow==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:v5P8EKVH3mKOM6C3hzYvEW5iUQy6xhA0dPbPs9moNI9Rdmz1JZp5bfYL,iv:DasnY/h4mw2YwSvdfA+reX6TuiBJkCiqhChhvGybDTM=,tag:ZKbk8h69vKVWHC9pqMtG0g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:oIPj8qI=,iv:tHZhRb4TqZrN4sG12zj6kS33+XUEbEUGLqAx49scnFQ=,tag:XG+VHSIhhBCBYj9ZvBReTA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ZQkk+2rv0h4kSckijYUm,iv:sBoYwLN5hREvIRoCiA9VKgBp5jRvaGS3BnZ9YQ815bM=,tag:M0uUY2hlEHW1Q6nweD2mfA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Lv/RLmKkMitqEvJe7KlaIHBw9w8xZU+bVg==,iv:+Vx2kY5lOctZ4j/8ZQsFIdYHOpFbz2p2/jcO98cyiVo=,tag:yQHSDejhTKMUZUoe9zZGkg==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSEF6aUtPK3hEMjdnN3JZ
            dlB0K0QxYzczQmc1b05ScVE2WTJWVnc2ZFNvCmJWKzdGZmRMV3EyQUQyc0Z1RjlN
            akpHaTYxTWdaQzM4YW1NRWZwS0d0VlUKLS0tIHRtNEhKVkRxNnoxK29FQjJnL3FM
            NG0yQ2R1MUZ3QnZqZnB5WnNLYXJ6OXMK1QQi2vTzMz6Mil4v6Z+jI698+OZXUAKv
            8PB2r4LrsHtG8NDuV/k6O8TZnR/5p3U+UC69aUDKSM+mI5iewh+/xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T04:24:01Z"
    mac: ENC[AES256_GCM,data:dot8J2oY0YlvCKLKeTeUmuRMwbHTnMWImkka6UOPF7jas1GtDdoezCtvmVCk4FBItByhnULIy+s9BmoSDQRVBR2XdhmDfjQFCtBdFqeVEOb+3qVDashZqrvNHb1W13SvnqntQjodR8QYefRODceH/7yaoqnM0uBCOpTem+Jup2w=,iv:DmguRihuVMGULx56tyKXDLlkcRSi36bUUwWs57fr5Rk=,tag:OsyJa3iVkI7WlesYBgyH5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
