# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/rbac.authorization.k8s.io/clusterrole_v1.json
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:cnpg-dragonfly-read
  labels:
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
    rbac.kyverno.io/aggregate-to-background-controller: "true"
    rbac.kyverno.io/aggregate-to-reports-controller: "true"
rules:
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - dragonflydb.io
    resources:
      - dragonflies
    verbs:
      - get
      - list
      - watch
