# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# IMPORTANT: This file contains unencrypted secrets.
# Run `make sops-encrypt` or `sops --encrypt --in-place` before committing!
apiVersion: v1
kind: Secret
metadata:
    name: opencode-secret
    namespace: ai
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jzmmNP5OOmlfoS0cEv0YnZMo/6cpiiWvlPyvTDnsXH/RANEzxUcp,iv:OG2mTK+8m/yn6OlgP3iwkEw7OAH8j/E8L7aUt/DLlKg=,tag:mVWf7OHy07PnIPhlTXiB8g==,type:comment]
    #ENC[AES256_GCM,data:sQwpQb2di82Xy2dBplxtf6Ljud1k92OrKeqSRceX+aUU,iv:cLRWbYWjXlSigCxs521nCPyNY+uzzD3Ll+XBX38NJ0s=,tag:LAXrpWDUvGKFxJUBjb8X+g==,type:comment]
    #ENC[AES256_GCM,data:K2uybZwGJyhSHKwGXQOkSNYcIlmfHywe27yn,iv:t8vpgkOc8DssqtWEG4IwNQb43MSmHbBFoNgyb9RmOGQ=,tag:O9fM8EjNdUcnFc1Bu5i3jg==,type:comment]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:gWYbPt/1+EVSIJjgQWy09bU=,iv:A3kZpK7WLJJaIT2skcP24dmF/OICjZNGHGpZeo7WBhc=,tag:nX0EQbnOliGL1f/ERbLluQ==,type:str]
    #ENC[AES256_GCM,data:/0AOhJh4fAsylPqzknvdErg6xMYO6uGuyZ51NjTV6/aXmu4=,iv:8CeFKurw6SBf03rmuRu6ZN1QFMhglCxsLhJbI7YM2RM=,tag:TgNQe+Gg18Z8oIRbhAXnBA==,type:comment]
    #ENC[AES256_GCM,data:7N3ivqaL5sDjqBsUxIVJN3JUBk0GNe4PjEDJRasVV7JCSZZQVw==,iv:BIu4UbPMS+SYWGLL7ZHE0HDPeGlopiehWad4HbZ906w=,tag:6G1t3OYzLSaTjdrEcMUzuQ==,type:comment]
    #ENC[AES256_GCM,data:yPJybS1OtT74myj2rW6HbJNNe04doMvFTKu6Ni8L9grkH8JgqNQ5tpZWUzeYGA/w,iv:Hh/MZzwvmGKy3wCbn/0yE6yvuFvBinGMjK0EUVzZKG4=,tag:EgY/ARWHqcwF5WOAecM00g==,type:comment]
    #ENC[AES256_GCM,data:Y9Nf6B1MpdKkZS02X0nbJnG2/SkVkKTAvzjkxwlmfs6x4EwTJamgwIayeg==,iv:RRIewvNfLtCzW7YU3ipPzSUQOPy3NQxVyDL2EFYRv1M=,tag:F8mrBrDoo3RA0IeQGmxveg==,type:comment]
    OPENCODE_SERVER_USERNAME: ENC[AES256_GCM,data:H9BD/IDpc0c=,iv:c+6k7gMOukXneYM0gslWYHrlCncmGQ+X05U4No6PbDU=,tag:aNWjkdzkRhc1hcUM/MU/2g==,type:str]
    #ENC[AES256_GCM,data:LCnrRZ1gOYwg85jApgxff+ErrKRUAARxftu9yg4IUCkZErffPhA6UvF6yBYCs477cgAnG5Gpkh7STxU=,iv:hfwo9/VbOuU/hS/va5Ny9zn4EwjYyDlyFkX22mavdnk=,tag:6zvLhn/7jCMfa/DGuAqR1Q==,type:comment]
    #ENC[AES256_GCM,data:0hCHRLIzLGu8rCMivEgkVJkQddCSjb4pYrpmAapSPuUSAie3iUz+6wKXw3V+dO13CChQsA==,iv:NIOLzuMYNi1/YLe92et4VCEKWOdePAaIvPSqIFIw93s=,tag:R5TJ/Ji0oIG9WqOmEqvXzA==,type:comment]
    #ENC[AES256_GCM,data:qw6OOfyW/4hHtQ3qXfe3/YCRL72bN2hA4S62fE7Y392cPq6DPlIc3uGmwaM=,iv:Hv+VnK4AZZsT99MKP+VOFDd3nFaI7AXzSls3lCKe8sk=,tag:+yLQpDHSUa1EkLCI/iOVvw==,type:comment]
    #ENC[AES256_GCM,data:Atet0RvC0lzT1q9wVPkvYN0RlAVPnAvSCBvuBOZnPqNtcImK8Fw=,iv:AUYvwbug3Wx5Uf0mWqVObpO7PlISKh9JRLMcnl8KtFY=,tag:ubMKKNNPuPz4Vawx31+b1Q==,type:comment]
    #ENC[AES256_GCM,data:Zxr4y2vkPbCUossoqvmjKURmijEFZF8hLIFLfKSI9F5Pk9bfglfnOsg12jJsYw==,iv:pCa0aLpwU4xacsNGKOhTPj/BCYucGEVHcArt4yTxu+g=,tag:emuY4znZJr3twpXuDvu7bQ==,type:comment]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZVRmTjhnZzR0N3JrMGF4
            WjRabUhRNXd0TW1ZMEFLb2RGSHRUbERnSmtRClV0aDhYOTFoVXFDYVZmUFNzZXhQ
            cFEwZkUzVXZlRFIxUWxWOGNnL2dibUEKLS0tIExBOE9NMHo3VnZuRmVjWi9KcFFm
            R0F4dVlsL0FCWmN5dTFVcWdOZHpCeTgKyJBQMbFDRFCRF9GJ9Fc2cVPHBdb1bd3b
            UfgqYnp/ni7w7wKoudXnVPrAFVrMngPO/zplRVE0UTDwX3QyU921RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T01:32:40Z"
    mac: ENC[AES256_GCM,data:EKjSUxq4YR+U4jd7J/Q/j7SNyVgujHmNdlHhz5ubF+/HaFsZq/FOsppb85Tb1otQrhWSuRcQsTYFwwCeUcmB9cemw2keViNxUJmqPDR5hHjgVJYqZOwZnduuu/NALshVjT4vSkyrgWOCdtGdpCRVhscZhgga0Dt5j4hzbw4p/30=,iv:eSRD7MgdPzpj6a8rpjwzuLSQ1AZROan6QGlDFkxrZtA=,tag:Okx5IRMSVGvsyidVY1e5RA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
