# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# IMPORTANT: This file contains unencrypted secrets.
# Run `make sops-encrypt` or `sops --encrypt --in-place` before committing!
apiVersion: v1
kind: Secret
metadata:
    name: opencode-secret
    namespace: ai
type: Opaque
stringData:
    #ENC[AES256_GCM,data:GlBdBWAyHfC2mLK9TqLq8Ofdx/Ybwramkg4JDK+lxdBL2Drx91KL,iv:6dB08u6PFLIasWzk3Ro4x/aPXmqdsTyJYXr2eJ86zgA=,tag:HHuTSkisAgZNjDKsRPFlSg==,type:comment]
    #ENC[AES256_GCM,data:No/1JjTsm7PA+TSctcWd2Fxb/vMdV9hS8Cu9oV+sztr/,iv:FGIUrExH66qvK2SgQ/pzMjoixyFtYqlS2CqQoTJmF1A=,tag:09mw3mzfmfjbAbpztC0AnQ==,type:comment]
    #ENC[AES256_GCM,data:mV2iDJmsolsy+wdjlFcwjQixxMG8kZ8v7uZf,iv:2QuQqSV7Rwbp6AaXalUEAnSB3sXu2ejgbKn0QJkmbVo=,tag:VOYoxlMPZ5ixlNhOL1r7Ow==,type:comment]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:RnYo5RoWbmsDXOr50L0l15A=,iv:Ne/FEcWfwcYF6FWOfxZ/bM68siNgJFFF6csfQd1CrZY=,tag:GXxlr73Iht6vOqIPJIGm+w==,type:str]
    #ENC[AES256_GCM,data:LR7z4MqeVFMM4mhgY2YUTWl7l2RmLck9evuYvqBZ6QIttf4=,iv:WHu7xgIHxFs76kT99QacwXRXmSA2ZERBjnZ4SNoRzec=,tag:20nwn6W3paHhErGUqV/cwA==,type:comment]
    #ENC[AES256_GCM,data:uGg0uwZBx8/hKDQxQtfScs9LfnmXhQUwMqH4yodDtKYACrX7PQ==,iv:0CIHe2Se9hAuc3dtqNHd/wdinRv46ilvYvMJHgMXZsw=,tag:XqfMdmG/Xg0BBDfbSCKRjQ==,type:comment]
    #ENC[AES256_GCM,data:GYleHMSysSg3T/IzAzCxblVEL3QS4Jh108GpNLPCWv25twwszn3e5sjRpALt0DYt,iv:OBAh+n17h3MEHrIRde1j8VzyyCe4KftAlvmO/Vc9Sa8=,tag:mceFuV/WRGoRfXm0tHU/vA==,type:comment]
    #ENC[AES256_GCM,data:xwvy/kUartp6dTVheZJtwFQaF1x9o1Lmh8dAQssm7j9Yrt0pJEBRvjQkBg==,iv:WPOMAOjkFrrdj6HoAFIueSOgvYzAhgsr/R7cNr5skCM=,tag:qDzUTvOtFqW6dM9M12mNTA==,type:comment]
    OPENCODE_SERVER_USERNAME: ENC[AES256_GCM,data:oEezrpibE0A=,iv:HGa+flsKfdRNrZbLwmwkZaUja+JPcQQvO/5vsU6FYTY=,tag:txh2MJM7C2FvoSeCTENF3w==,type:str]
    #ENC[AES256_GCM,data:HlbgDWynkgjlnc/H1aM8vs37P9NUS8SdT6eq5bTAk6KoS4Pd93x+/FdroPvzi0vCseCc35NKbCKbzo0=,iv:I1TAWGYKTg2GKYA+xZdRgzrMxaXQi20ESAf86r7ee40=,tag:n22ZYq2gnkcC9CiGm/ylrw==,type:comment]
    OPENCODE_SERVER_PASSWORD: ENC[AES256_GCM,data:72TcRLRClkpClwmbSvxUPblWDYyihmzPiQ==,iv:DsQ4Sw3MNuM1Ak3rsweypkyjnZNmf8DeR6EWsWLOB+w=,tag:ObB1iJQmPtb7aESfWn1rIA==,type:str]
    #ENC[AES256_GCM,data:6t3HM6pJ9wX4wQIXWZdaIVvV3EwbHC78iv0N5bS++vUV1gdNomQDWJXJ360=,iv:F6p3P2cJqR/78xvc4mUoTs3LKaA2WH1BF90PDar7hFM=,tag:pK0SXP4airGmxrYqXUJtEQ==,type:comment]
    #ENC[AES256_GCM,data:1IRS5KTszgB3W9CJawz2OwenlQCgNH7RQU3744BCFCI/U5Klgog=,iv:BARKhreEJ7oGLKNlobn5AtfNOXMNUUy+J4z/j53ODB4=,tag:7nmiEYJAoM+qL8b16WnU9A==,type:comment]
    #ENC[AES256_GCM,data:3rXM5Dn27YrHjVm9zWhDOKIEeT+pMit2gPch6+1/TswMlwWl/QQisPCi2flxKw==,iv:MmvZSUVHMGshL4Bl0vir9QBYDL2lQGIUhUHzAfoXMbg=,tag:JOgXcDWqwixklNuAT2/52w==,type:comment]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNd0IyOHVpQWh2L0M3VVBj
            M2hTa1NUUWpNeHBBbEFuM2tNSHV2SENEMEdvCm1LMnFvUllxYTBZL3MrQm1WOGM0
            ajJ4NG1pcjd2VWpmV3ZrbStvMDlTNUEKLS0tIENpODI5U2QweG83VnExZG1iWk5k
            V1E3R2x1ZnJRYUlYQktUamxydVlVeEkKZdssOEBV/3QU8NxJgYTcT+CubaQK4hZS
            fLP3urBXayJkZZfMSiIXpk1XMe06ppN5oQBbF5P7bjNbsocUge77ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T19:00:10Z"
    mac: ENC[AES256_GCM,data:8MCykx6gBPzwMleL3QMXXVMiwC030CN5FJCBXfnIuwTHO/mjnqVfBqMkVdYAfijTot30oFA3rXgPxRR7TXAItcB4O3/zOAcwo8lwL5NiiRS5Hsk7B64J5LzuUC3bKObzv5V4L39UFCojs3OmIorUs2aE4ZnH+Mq7h7a9AGuqdgU=,iv:fE3E8NdhUHB9TVLcF4axK2MuoPC8h2myNmAhbgseuss=,tag:dmu0W9VAmH3est1GF+Rftg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
