# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# IMPORTANT: This file contains unencrypted secrets.
# Run `make sops-encrypt` or `sops --encrypt --in-place` before committing!
apiVersion: v1
kind: Secret
metadata:
    name: opencode-secret
    namespace: ai
type: Opaque
stringData:
    #ENC[AES256_GCM,data:+MtTFNbiL2J+Y+MzqSG4e0gdoveJ6sWd2mdcdrQe2rJg7oPRHakA,iv:4Nf4/Jr+884riibQnngeTFN1HMetcKMp5N3y1uMrA30=,tag:pecGmrdwG9X4IwPkC9jmgA==,type:comment]
    #ENC[AES256_GCM,data:o6aPpMk5C02aFcLarZHzcYH2eUo+CMwX0j2mNti2YhAh,iv:c9+4ZJK+HoVDRQYM5N/IH3VIWTH2LkKM12Z+VECoTgk=,tag:ObT/UMcqg4F0uqKWKeYaVQ==,type:comment]
    #ENC[AES256_GCM,data:POIk9ptaNiRwrx4ZcULDrjskB8Val8AYgYYl,iv:yybKLD/qxr6fTwh5T8OSfVBWhorhaJbcaF5aVjw1HH0=,tag:g2xTKUFp+GOXP8ko7hO6aQ==,type:comment]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:XwAs0LL6YZBETdpKICbAh5Q=,iv:nQhyKpce7ujthZZ/Z2bbGk83S1FrMboWtem0EEKI3Fg=,tag:7bJWMH94w1fCDpfSWZAZSA==,type:str]
    #ENC[AES256_GCM,data:kHb3pFxkrhZKyiHCGrehxGvj7RMPHIf1fyf8K/9KXhHpaaw=,iv:AbeMKf8a++NySh6JGyAUBtD5ziCKJw2pB7uZ3hzCdmA=,tag:9qsajtTCKbrasPEz8/eM6Q==,type:comment]
    #ENC[AES256_GCM,data:5Hc1jxroR6/iLNQp1NSOlerDcw4+lw/Kv6udv4V00M4beCJ/bw==,iv:U6uLuQzBnQfYACaBZ7bGKivk1B9d2yCZstjDPyNEUss=,tag:16+VNEY2i38e/RzYFEodwA==,type:comment]
    #ENC[AES256_GCM,data:T9ovw0P5E/9EufFqa5HPeNPnbZzevPcnmLeYsJa24Qak6kHFGaGEh1Fs1KiQJYKM,iv:P9voIjxN4QA8NrK9tilNJy1ZEK1oxU9beQzK/a63W7s=,tag:YNZlZYRPR7R5I2rTXP7BHw==,type:comment]
    #ENC[AES256_GCM,data:YTc5eJkMQvYRNfQhb00voThRO+IhteXLdtwrj4Y50J+KfNQxX50KkCqrjA==,iv:ZSXcSiJr5MgG5RMqkTDmiHSBQ3zuiiXnfxNkg/bkPno=,tag:3nMUY5Wl2M+f+AGfHJ/6Kw==,type:comment]
    OPENCODE_SERVER_USERNAME: ENC[AES256_GCM,data:5Bna6j8VKLM=,iv:+2Npn5GsF7EPrZykd5DlHPHTBxxayVHhIeRBmdTvpxI=,tag:jlbnG3zhsq86nNZT5Ps3Fw==,type:str]
    #ENC[AES256_GCM,data:v1PNwzxh2nejOBqpSp9oGndHXGTkvjQyfyfzLnxym036rdnqCYCJuylxs+lNuLD2cbf+PI4CGOWZCds=,iv:2eK8H16vGZJHxJe3MDRtCpfafAMI1tUD1ZSR/jeY28k=,tag:6cuPeg3cNO7vZbwioclIZg==,type:comment]
    OPENCODE_SERVER_PASSWORD: ENC[AES256_GCM,data:rlYMtBPMxoLuNJXcJok3Se58Sz2eTGFfJQ==,iv:CZrYOtyAjXEprg19nwobfncjbJbDmAofL0fWrzXZZs4=,tag:ZazkCTrQ+mVnWAfVhaeowQ==,type:str]
    #ENC[AES256_GCM,data:SszI9oCA5ou4NxLaVtlI9GzepthBJ+hQL2i+ndM4UgSSLofODvjQoQfJ+vE=,iv:k62ycn+B1zqrBT1yZ6Z6jDWhYSPV9O0bIkjGjHEtP1Y=,tag:BbQHUtsyvIONLz2VenF9Pg==,type:comment]
    #ENC[AES256_GCM,data:ApUrqTw/O7iov5e6Xp6HE4v7ingt4vSiJSbFCByn6toZZ33WmW4=,iv:AspG5fZ9CfxTN9gx92N6aL/BU4Ta37Pjp6TP06XjFvk=,tag:LFxkGxwu/LySkQqV1trcMA==,type:comment]
    #ENC[AES256_GCM,data:fwh/SAnX6Xa/f8HtodE7R2qIqSAPg5pv/WdUSZ7YymqrR0dlO3LE+PI5Yy0V3w==,iv:Nhjz/IOfiQhWsSglNM1Ga3a/AYkIvQmM0eRe0N20/gI=,tag:rDlyOsfiOuUUo7ewoZPC7A==,type:comment]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeXNkTUdEYWFzQzVobENx
            SGlLdDJaalBpMjljOHJ3WG05QmRSdDNLaFJRCnJRRHpJSkwraXY4UFpZMDZML1do
            SzZjUE1NRW1OK1YvaS82dUd2eGRRQ0kKLS0tIGlTT3hpdWdUNmlVeHNWUDYwdllq
            U0g4enU3ZVhpN0VDTk5UNHROTmtQY00KJT2V2676/ZlZ6k0O86rpD30Yovx6mDkZ
            6T71WjVNjO5OSP0FdfsWBOqG6ompJkP5rUw8NhjklxpWznzTWN+sDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T02:35:07Z"
    mac: ENC[AES256_GCM,data:NxeoeAsk2NkJJ14jZYXVt0xQ8sh0NxFKZgr+CYdjIJeQpLnrsb3o3vLeVtZkuSdD2MC7XX/hCgQ+Gpegv4caL34HOOgc+1NzfLKm6ThTnJejETios9rRHWba9idhs9KGGK7CBdjmq7cwqB5+k99OyW9g6frbVHJ5m2TrG5uvFh8=,iv:7HW0kneWtjtW6+Ibem6wK+KhSvnH258/vsoA4+BV9n0=,tag:D8Ob9lyhpWPPiUsn3fQL5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
